from typing import Any

class V1AWSElasticBlockStoreVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, fs_type: str, partition: int, read_only: bool, volume_id: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def fs_type(self) -> str: ...
    @fs_type.setter
    def fs_type(self, fs_type: str) -> None: ...
    @property
    def partition(self) -> int: ...
    @partition.setter
    def partition(self, partition: int) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @read_only.setter
    def read_only(self, read_only: bool) -> None: ...
    @property
    def volume_id(self) -> str: ...
    @volume_id.setter
    def volume_id(self, volume_id: str) -> None: ...
