from typing import Any

class V1ContainerResizePolicy:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, resource_name: str, restart_policy: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def resource_name(self) -> str: ...
    @resource_name.setter
    def resource_name(self, resource_name: str) -> None: ...
    @property
    def restart_policy(self) -> str: ...
    @restart_policy.setter
    def restart_policy(self, restart_policy: str) -> None: ...
