from kubernetes_asyncio.client.models import V1CronJobSpec
from kubernetes_asyncio.client.models import V1CronJobStatus
from kubernetes_asyncio.client.models import V1ObjectMeta
from typing import Any

class V1CronJob:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str, kind: str, metadata: V1ObjectMeta, spec: V1CronJobSpec, status: V1CronJobStatus, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
    @property
    def spec(self) -> V1CronJobSpec: ...
    @spec.setter
    def spec(self, spec: V1CronJobSpec) -> None: ...
    @property
    def status(self) -> V1CronJobStatus: ...
    @status.setter
    def status(self, status: V1CronJobStatus) -> None: ...
