from kubernetes_asyncio.client.models import V1ObjectMeta
from typing import Any

class V1ConfigMap:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str, binary_data: dict[str, str], data: dict[str, str], immutable: bool, kind: str, metadata: V1ObjectMeta, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def binary_data(self) -> dict[str, str]: ...
    @binary_data.setter
    def binary_data(self, binary_data: dict[str, str]) -> None: ...
    @property
    def data(self) -> dict[str, str]: ...
    @data.setter
    def data(self, data: dict[str, str]) -> None: ...
    @property
    def immutable(self) -> bool: ...
    @immutable.setter
    def immutable(self, immutable: bool) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
