from kubernetes_asyncio.client.models import RbacV1Subject
from kubernetes_asyncio.client.models import V1ObjectMeta
from kubernetes_asyncio.client.models import V1RoleRef
from typing import Any

class V1ClusterRoleBinding:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str, kind: str, metadata: V1ObjectMeta, role_ref: V1RoleRef, subjects: list[RbacV1Subject], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
    @property
    def role_ref(self) -> V1RoleRef: ...
    @role_ref.setter
    def role_ref(self, role_ref: V1RoleRef) -> None: ...
    @property
    def subjects(self) -> list[RbacV1Subject]: ...
    @subjects.setter
    def subjects(self, subjects: list[RbacV1Subject]) -> None: ...
