from typing import Any

class V1EmptyDirVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, medium: str, size_limit: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def medium(self) -> str: ...
    @medium.setter
    def medium(self, medium: str) -> None: ...
    @property
    def size_limit(self) -> str: ...
    @size_limit.setter
    def size_limit(self, size_limit: str) -> None: ...
