from kubernetes_asyncio.client.models import V1ConfigMapEnvSource
from kubernetes_asyncio.client.models import V1SecretEnvSource
from typing import Any

class V1EnvFromSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, config_map_ref: V1ConfigMapEnvSource, prefix: str, secret_ref: V1SecretEnvSource, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def config_map_ref(self) -> V1ConfigMapEnvSource: ...
    @config_map_ref.setter
    def config_map_ref(self, config_map_ref: V1ConfigMapEnvSource) -> None: ...
    @property
    def prefix(self) -> str: ...
    @prefix.setter
    def prefix(self, prefix: str) -> None: ...
    @property
    def secret_ref(self) -> V1SecretEnvSource: ...
    @secret_ref.setter
    def secret_ref(self, secret_ref: V1SecretEnvSource) -> None: ...
