from typing import Any

class V1ExecAction:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, command: list[str], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def command(self) -> list[str]: ...
    @command.setter
    def command(self, command: list[str]) -> None: ...
