from typing import Any

class V1EventSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, component: str, host: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def component(self) -> str: ...
    @component.setter
    def component(self, component: str) -> None: ...
    @property
    def host(self) -> str: ...
    @host.setter
    def host(self, host: str) -> None: ...
