from typing import Any

class V1FlockerVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, dataset_name: str, dataset_uuid: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def dataset_name(self) -> str: ...
    @dataset_name.setter
    def dataset_name(self, dataset_name: str) -> None: ...
    @property
    def dataset_uuid(self) -> str: ...
    @dataset_uuid.setter
    def dataset_uuid(self, dataset_uuid: str) -> None: ...
