from typing import Any

class V1GroupVersionForDiscovery:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, group_version: str, version: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def group_version(self) -> str: ...
    @group_version.setter
    def group_version(self, group_version: str) -> None: ...
    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, version: str) -> None: ...
