from kubernetes_asyncio.client.models import V1IngressPortStatus
from typing import Any

class V1IngressLoadBalancerIngress:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, hostname: str, ip: str, ports: list[V1IngressPortStatus], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def hostname(self) -> str: ...
    @hostname.setter
    def hostname(self, hostname: str) -> None: ...
    @property
    def ip(self) -> str: ...
    @ip.setter
    def ip(self, ip: str) -> None: ...
    @property
    def ports(self) -> list[V1IngressPortStatus]: ...
    @ports.setter
    def ports(self, ports: list[V1IngressPortStatus]) -> None: ...
