from kubernetes_asyncio.client.models import V1IngressLoadBalancerIngress
from typing import Any

class V1IngressLoadBalancerStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, ingress: list[V1IngressLoadBalancerIngress], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def ingress(self) -> list[V1IngressLoadBalancerIngress]: ...
    @ingress.setter
    def ingress(self, ingress: list[V1IngressLoadBalancerIngress]) -> None: ...
