from typing import Any

class V1IPBlock:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, cidr: str, _except: list[str], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def _except(self) -> list[str]: ...
    @_except.setter
    def _except(self, _except: list[str]) -> None: ...
    @property
    def cidr(self) -> str: ...
    @cidr.setter
    def cidr(self, cidr: str) -> None: ...
