from typing import Any

class V1ImageVolumeStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, image_ref: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def image_ref(self) -> str: ...
    @image_ref.setter
    def image_ref(self, image_ref: str) -> None: ...
