from datetime import datetime
from kubernetes_asyncio.client.models import V1JobCondition
from kubernetes_asyncio.client.models import V1UncountedTerminatedPods
from typing import Any

class V1JobStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, active: int, completed_indexes: str, completion_time: datetime, conditions: list[V1JobCondition], failed: int, failed_indexes: str, ready: int, start_time: datetime, succeeded: int, terminating: int, uncounted_terminated_pods: V1UncountedTerminatedPods, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def active(self) -> int: ...
    @active.setter
    def active(self, active: int) -> None: ...
    @property
    def completed_indexes(self) -> str: ...
    @completed_indexes.setter
    def completed_indexes(self, completed_indexes: str) -> None: ...
    @property
    def completion_time(self) -> datetime: ...
    @completion_time.setter
    def completion_time(self, completion_time: datetime) -> None: ...
    @property
    def conditions(self) -> list[V1JobCondition]: ...
    @conditions.setter
    def conditions(self, conditions: list[V1JobCondition]) -> None: ...
    @property
    def failed(self) -> int: ...
    @failed.setter
    def failed(self, failed: int) -> None: ...
    @property
    def failed_indexes(self) -> str: ...
    @failed_indexes.setter
    def failed_indexes(self, failed_indexes: str) -> None: ...
    @property
    def ready(self) -> int: ...
    @ready.setter
    def ready(self, ready: int) -> None: ...
    @property
    def start_time(self) -> datetime: ...
    @start_time.setter
    def start_time(self, start_time: datetime) -> None: ...
    @property
    def succeeded(self) -> int: ...
    @succeeded.setter
    def succeeded(self, succeeded: int) -> None: ...
    @property
    def terminating(self) -> int: ...
    @terminating.setter
    def terminating(self, terminating: int) -> None: ...
    @property
    def uncounted_terminated_pods(self) -> V1UncountedTerminatedPods: ...
    @uncounted_terminated_pods.setter
    def uncounted_terminated_pods(self, uncounted_terminated_pods: V1UncountedTerminatedPods) -> None: ...
