from typing import Any

class V1KeyToPath:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, key: str, mode: int, path: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def key(self) -> str: ...
    @key.setter
    def key(self, key: str) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, mode: int) -> None: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, path: str) -> None: ...
