from kubernetes_asyncio.client.models import V1LimitResponse
from typing import Any

class V1LimitedPriorityLevelConfiguration:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, borrowing_limit_percent: int, lendable_percent: int, limit_response: V1LimitResponse, nominal_concurrency_shares: int, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def borrowing_limit_percent(self) -> int: ...
    @borrowing_limit_percent.setter
    def borrowing_limit_percent(self, borrowing_limit_percent: int) -> None: ...
    @property
    def lendable_percent(self) -> int: ...
    @lendable_percent.setter
    def lendable_percent(self, lendable_percent: int) -> None: ...
    @property
    def limit_response(self) -> V1LimitResponse: ...
    @limit_response.setter
    def limit_response(self, limit_response: V1LimitResponse) -> None: ...
    @property
    def nominal_concurrency_shares(self) -> int: ...
    @nominal_concurrency_shares.setter
    def nominal_concurrency_shares(self, nominal_concurrency_shares: int) -> None: ...
