from kubernetes_asyncio.client.models import V1NodeRuntimeHandlerFeatures
from typing import Any

class V1NodeRuntimeHandler:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, features: V1NodeRuntimeHandlerFeatures, name: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def features(self) -> V1NodeRuntimeHandlerFeatures: ...
    @features.setter
    def features(self, features: V1NodeRuntimeHandlerFeatures) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
