from typing import Any

class V1NodeAllocatableResourceClaimStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, containers: list[str] | None = None, resource_claim_name: str | None = None, resources: dict[str, str] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def containers(self) -> list[str]: ...
    @containers.setter
    def containers(self, containers: list[str]) -> None: ...
    @property
    def resource_claim_name(self) -> str: ...
    @resource_claim_name.setter
    def resource_claim_name(self, resource_claim_name: str) -> None: ...
    @property
    def resources(self) -> dict[str, str]: ...
    @resources.setter
    def resources(self, resources: dict[str, str]) -> None: ...
