from kubernetes_asyncio.client.models import V1NodeSwapStatus
from typing import Any

class V1NodeSystemInfo:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, architecture: str, boot_id: str, container_runtime_version: str, kernel_version: str, kube_proxy_version: str, kubelet_version: str, machine_id: str, operating_system: str, os_image: str, swap: V1NodeSwapStatus, system_uuid: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def architecture(self) -> str: ...
    @architecture.setter
    def architecture(self, architecture: str) -> None: ...
    @property
    def boot_id(self) -> str: ...
    @boot_id.setter
    def boot_id(self, boot_id: str) -> None: ...
    @property
    def container_runtime_version(self) -> str: ...
    @container_runtime_version.setter
    def container_runtime_version(self, container_runtime_version: str) -> None: ...
    @property
    def kernel_version(self) -> str: ...
    @kernel_version.setter
    def kernel_version(self, kernel_version: str) -> None: ...
    @property
    def kube_proxy_version(self) -> str: ...
    @kube_proxy_version.setter
    def kube_proxy_version(self, kube_proxy_version: str) -> None: ...
    @property
    def kubelet_version(self) -> str: ...
    @kubelet_version.setter
    def kubelet_version(self, kubelet_version: str) -> None: ...
    @property
    def machine_id(self) -> str: ...
    @machine_id.setter
    def machine_id(self, machine_id: str) -> None: ...
    @property
    def operating_system(self) -> str: ...
    @operating_system.setter
    def operating_system(self, operating_system: str) -> None: ...
    @property
    def os_image(self) -> str: ...
    @os_image.setter
    def os_image(self, os_image: str) -> None: ...
    @property
    def swap(self) -> V1NodeSwapStatus: ...
    @swap.setter
    def swap(self, swap: V1NodeSwapStatus) -> None: ...
    @property
    def system_uuid(self) -> str: ...
    @system_uuid.setter
    def system_uuid(self, system_uuid: str) -> None: ...
