from typing import Any

class V1NodeFeatures:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, supplemental_groups_policy: bool, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def supplemental_groups_policy(self) -> bool: ...
    @supplemental_groups_policy.setter
    def supplemental_groups_policy(self, supplemental_groups_policy: bool) -> None: ...
