from typing import Any

class V1OwnerReference:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str, block_owner_deletion: bool, controller: bool, kind: str, name: str, uid: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def block_owner_deletion(self) -> bool: ...
    @block_owner_deletion.setter
    def block_owner_deletion(self, block_owner_deletion: bool) -> None: ...
    @property
    def controller(self) -> bool: ...
    @controller.setter
    def controller(self, controller: bool) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def uid(self) -> str: ...
    @uid.setter
    def uid(self, uid: str) -> None: ...
