from typing import Any

class V1PodReadinessGate:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, condition_type: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def condition_type(self) -> str: ...
    @condition_type.setter
    def condition_type(self, condition_type: str) -> None: ...
