from typing import Any

class V1PodIP:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, ip: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def ip(self) -> str: ...
    @ip.setter
    def ip(self, ip: str) -> None: ...
