from typing import Any

class V1PodSchedulingGroup:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, pod_group_name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def pod_group_name(self) -> str: ...
    @pod_group_name.setter
    def pod_group_name(self, pod_group_name: str) -> None: ...
