from kubernetes_asyncio.client.models import V1LocalObjectReference
from typing import Any

class V1RBDVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, fs_type: str, image: str, keyring: str, monitors: list[str], pool: str, read_only: bool, secret_ref: V1LocalObjectReference, user: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def fs_type(self) -> str: ...
    @fs_type.setter
    def fs_type(self, fs_type: str) -> None: ...
    @property
    def image(self) -> str: ...
    @image.setter
    def image(self, image: str) -> None: ...
    @property
    def keyring(self) -> str: ...
    @keyring.setter
    def keyring(self, keyring: str) -> None: ...
    @property
    def monitors(self) -> list[str]: ...
    @monitors.setter
    def monitors(self, monitors: list[str]) -> None: ...
    @property
    def pool(self) -> str: ...
    @pool.setter
    def pool(self, pool: str) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @read_only.setter
    def read_only(self, read_only: bool) -> None: ...
    @property
    def secret_ref(self) -> V1LocalObjectReference: ...
    @secret_ref.setter
    def secret_ref(self, secret_ref: V1LocalObjectReference) -> None: ...
    @property
    def user(self) -> str: ...
    @user.setter
    def user(self, user: str) -> None: ...
