from typing import Any

class V1ResourceQuotaStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, hard: dict[str, str], used: dict[str, str], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def hard(self) -> dict[str, str]: ...
    @hard.setter
    def hard(self, hard: dict[str, str]) -> None: ...
    @property
    def used(self) -> dict[str, str]: ...
    @used.setter
    def used(self, used: dict[str, str]) -> None: ...
