from kubernetes_asyncio.client.models import V1ResourceClaim
from typing import Any

class V1ResourceRequirements:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, claims: list[V1ResourceClaim], limits: dict[str, str], requests: dict[str, str], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def claims(self) -> list[V1ResourceClaim]: ...
    @claims.setter
    def claims(self, claims: list[V1ResourceClaim]) -> None: ...
    @property
    def limits(self) -> dict[str, str]: ...
    @limits.setter
    def limits(self, limits: dict[str, str]) -> None: ...
    @property
    def requests(self) -> dict[str, str]: ...
    @requests.setter
    def requests(self, requests: dict[str, str]) -> None: ...
