from typing import Any

class V1ServiceAccountTokenProjection:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, audience: str, expiration_seconds: int, path: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def audience(self) -> str: ...
    @audience.setter
    def audience(self, audience: str) -> None: ...
    @property
    def expiration_seconds(self) -> int: ...
    @expiration_seconds.setter
    def expiration_seconds(self, expiration_seconds: int) -> None: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, path: str) -> None: ...
