from typing import Any

class V1SuccessPolicyRule:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, succeeded_count: int, succeeded_indexes: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def succeeded_count(self) -> int: ...
    @succeeded_count.setter
    def succeeded_count(self, succeeded_count: int) -> None: ...
    @property
    def succeeded_indexes(self) -> str: ...
    @succeeded_indexes.setter
    def succeeded_indexes(self, succeeded_indexes: str) -> None: ...
