from typing import Any

class V1StatefulSetOrdinals:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, start: int, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def start(self) -> int: ...
    @start.setter
    def start(self, start: int) -> None: ...
