from typing import Any

class V1ScaleStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, replicas: int, selector: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def replicas(self) -> int: ...
    @replicas.setter
    def replicas(self, replicas: int) -> None: ...
    @property
    def selector(self) -> str: ...
    @selector.setter
    def selector(self, selector: str) -> None: ...
