from typing import Any

class V1TopologySelectorLabelRequirement:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, key: str, values: list[str], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def key(self) -> str: ...
    @key.setter
    def key(self, key: str) -> None: ...
    @property
    def values(self) -> list[str]: ...
    @values.setter
    def values(self, values: list[str]) -> None: ...
