from typing import Any

class V1UncountedTerminatedPods:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, failed: list[str], succeeded: list[str], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def failed(self) -> list[str]: ...
    @failed.setter
    def failed(self, failed: list[str]) -> None: ...
    @property
    def succeeded(self) -> list[str]: ...
    @succeeded.setter
    def succeeded(self, succeeded: list[str]) -> None: ...
