from typing import Any

class V1VolumeMount:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, mount_path: str, mount_propagation: str, name: str, read_only: bool, recursive_read_only: str, sub_path: str, sub_path_expr: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def mount_path(self) -> str: ...
    @mount_path.setter
    def mount_path(self, mount_path: str) -> None: ...
    @property
    def mount_propagation(self) -> str: ...
    @mount_propagation.setter
    def mount_propagation(self, mount_propagation: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @read_only.setter
    def read_only(self, read_only: bool) -> None: ...
    @property
    def recursive_read_only(self) -> str: ...
    @recursive_read_only.setter
    def recursive_read_only(self, recursive_read_only: str) -> None: ...
    @property
    def sub_path(self) -> str: ...
    @sub_path.setter
    def sub_path(self, sub_path: str) -> None: ...
    @property
    def sub_path_expr(self) -> str: ...
    @sub_path_expr.setter
    def sub_path_expr(self, sub_path_expr: str) -> None: ...
