from kubernetes_asyncio.client.models import V1ImageVolumeStatus
from typing import Any

class V1VolumeStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, image: V1ImageVolumeStatus | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def image(self) -> V1ImageVolumeStatus: ...
    @image.setter
    def image(self, image: V1ImageVolumeStatus) -> None: ...
