from typing import Any

class V1VsphereVirtualDiskVolumeSource:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, fs_type: str, storage_policy_id: str, storage_policy_name: str, volume_path: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def fs_type(self) -> str: ...
    @fs_type.setter
    def fs_type(self, fs_type: str) -> None: ...
    @property
    def storage_policy_id(self) -> str: ...
    @storage_policy_id.setter
    def storage_policy_id(self, storage_policy_id: str) -> None: ...
    @property
    def storage_policy_name(self) -> str: ...
    @storage_policy_name.setter
    def storage_policy_name(self, storage_policy_name: str) -> None: ...
    @property
    def volume_path(self) -> str: ...
    @volume_path.setter
    def volume_path(self, volume_path: str) -> None: ...
