# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.30.1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from kubernetes_asyncio.client.configuration import Configuration


class V1alpha2ResourceFilter(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'driver_name': 'str',
        'named_resources': 'V1alpha2NamedResourcesFilter'
    }

    attribute_map = {
        'driver_name': 'driverName',
        'named_resources': 'namedResources'
    }

    def __init__(self, driver_name=None, named_resources=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha2ResourceFilter - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default()
        self.local_vars_configuration = local_vars_configuration

        self._driver_name = None
        self._named_resources = None
        self.discriminator = None

        if driver_name is not None:
            self.driver_name = driver_name
        if named_resources is not None:
            self.named_resources = named_resources

    @property
    def driver_name(self):
        """Gets the driver_name of this V1alpha2ResourceFilter.  # noqa: E501

        DriverName is the name used by the DRA driver kubelet plugin.  # noqa: E501

        :return: The driver_name of this V1alpha2ResourceFilter.  # noqa: E501
        :rtype: str
        """
        return self._driver_name

    @driver_name.setter
    def driver_name(self, driver_name):
        """Sets the driver_name of this V1alpha2ResourceFilter.

        DriverName is the name used by the DRA driver kubelet plugin.  # noqa: E501

        :param driver_name: The driver_name of this V1alpha2ResourceFilter.  # noqa: E501
        :type driver_name: str
        """

        self._driver_name = driver_name

    @property
    def named_resources(self):
        """Gets the named_resources of this V1alpha2ResourceFilter.  # noqa: E501


        :return: The named_resources of this V1alpha2ResourceFilter.  # noqa: E501
        :rtype: V1alpha2NamedResourcesFilter
        """
        return self._named_resources

    @named_resources.setter
    def named_resources(self, named_resources):
        """Sets the named_resources of this V1alpha2ResourceFilter.


        :param named_resources: The named_resources of this V1alpha2ResourceFilter.  # noqa: E501
        :type named_resources: V1alpha2NamedResourcesFilter
        """

        self._named_resources = named_resources

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha2ResourceFilter):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha2ResourceFilter):
            return True

        return self.to_dict() != other.to_dict()
