from kubernetes_asyncio.client.models import V1alpha3DeviceClaimConfiguration
from kubernetes_asyncio.client.models import V1alpha3DeviceConstraint
from kubernetes_asyncio.client.models import V1alpha3DeviceRequest
from typing import Any

class V1alpha3DeviceClaim:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, config: list[V1alpha3DeviceClaimConfiguration], constraints: list[V1alpha3DeviceConstraint], requests: list[V1alpha3DeviceRequest], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def config(self) -> list[V1alpha3DeviceClaimConfiguration]: ...
    @config.setter
    def config(self, config: list[V1alpha3DeviceClaimConfiguration]) -> None: ...
    @property
    def constraints(self) -> list[V1alpha3DeviceConstraint]: ...
    @constraints.setter
    def constraints(self, constraints: list[V1alpha3DeviceConstraint]) -> None: ...
    @property
    def requests(self) -> list[V1alpha3DeviceRequest]: ...
    @requests.setter
    def requests(self, requests: list[V1alpha3DeviceRequest]) -> None: ...
