from kubernetes_asyncio.client.models import V1alpha2PodGroupTemplate
from kubernetes_asyncio.client.models import V1alpha2TypedLocalObjectReference
from typing import Any

class V1alpha2WorkloadSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, controller_ref: V1alpha2TypedLocalObjectReference | None = None, pod_group_templates: list[V1alpha2PodGroupTemplate] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def controller_ref(self) -> V1alpha2TypedLocalObjectReference: ...
    @controller_ref.setter
    def controller_ref(self, controller_ref: V1alpha2TypedLocalObjectReference) -> None: ...
    @property
    def pod_group_templates(self) -> list[V1alpha2PodGroupTemplate]: ...
    @pod_group_templates.setter
    def pod_group_templates(self, pod_group_templates: list[V1alpha2PodGroupTemplate]) -> None: ...
