from kubernetes_asyncio.client.models import V1alpha3OpaqueDeviceConfiguration
from typing import Any

class V1alpha3DeviceClassConfiguration:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, opaque: V1alpha3OpaqueDeviceConfiguration, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def opaque(self) -> V1alpha3OpaqueDeviceConfiguration: ...
    @opaque.setter
    def opaque(self, opaque: V1alpha3OpaqueDeviceConfiguration) -> None: ...
