from typing import Any

class V1alpha3DeviceAttribute:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, bool: bool, int: int, string: str, version: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def bool(self) -> bool: ...
    @bool.setter
    def bool(self, bool: bool) -> None: ...
    @property
    def int(self) -> int: ...
    @int.setter
    def int(self, int: int) -> None: ...
    @property
    def string(self) -> str: ...
    @string.setter
    def string(self, string: str) -> None: ...
    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, version: str) -> None: ...
