from typing import Any

class V1alpha3OpaqueDeviceConfiguration:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, driver: str, parameters: Any, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def driver(self) -> str: ...
    @driver.setter
    def driver(self, driver: str) -> None: ...
    @property
    def parameters(self) -> Any: ...
    @parameters.setter
    def parameters(self, parameters: Any) -> None: ...
