from kubernetes_asyncio.client.models import V1alpha3BasicDevice
from typing import Any

class V1alpha3Device:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, basic: V1alpha3BasicDevice, name: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def basic(self) -> V1alpha3BasicDevice: ...
    @basic.setter
    def basic(self, basic: V1alpha3BasicDevice) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
