from kubernetes_asyncio.client.models import V1ObjectMeta
from kubernetes_asyncio.client.models import V1alpha3ResourceClaimSpec
from kubernetes_asyncio.client.models import V1alpha3ResourceClaimStatus
from typing import Any

class V1alpha3ResourceClaim:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str, kind: str, metadata: V1ObjectMeta, spec: V1alpha3ResourceClaimSpec, status: V1alpha3ResourceClaimStatus, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ObjectMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ObjectMeta) -> None: ...
    @property
    def spec(self) -> V1alpha3ResourceClaimSpec: ...
    @spec.setter
    def spec(self, spec: V1alpha3ResourceClaimSpec) -> None: ...
    @property
    def status(self) -> V1alpha3ResourceClaimStatus: ...
    @status.setter
    def status(self, status: V1alpha3ResourceClaimStatus) -> None: ...
