from kubernetes_asyncio.client.models import V1alpha3DeviceClaim
from typing import Any

class V1alpha3ResourceClaimSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, devices: V1alpha3DeviceClaim, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def devices(self) -> V1alpha3DeviceClaim: ...
    @devices.setter
    def devices(self, devices: V1alpha3DeviceClaim) -> None: ...
