from kubernetes_asyncio.client.models import V1NodeSelector
from kubernetes_asyncio.client.models import V1alpha3DeviceAttribute
from kubernetes_asyncio.client.models import V1alpha3DeviceCounterConsumption
from kubernetes_asyncio.client.models import V1alpha3DeviceTaint
from typing import Any

class V1alpha3BasicDevice:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, all_nodes: bool, attributes: dict[str, V1alpha3DeviceAttribute], capacity: dict[str, str], consumes_counters: list[V1alpha3DeviceCounterConsumption], node_name: str, node_selector: V1NodeSelector, taints: list[V1alpha3DeviceTaint], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def all_nodes(self) -> bool: ...
    @all_nodes.setter
    def all_nodes(self, all_nodes: bool) -> None: ...
    @property
    def attributes(self) -> dict[str, V1alpha3DeviceAttribute]: ...
    @attributes.setter
    def attributes(self, attributes: dict[str, V1alpha3DeviceAttribute]) -> None: ...
    @property
    def capacity(self) -> dict[str, str]: ...
    @capacity.setter
    def capacity(self, capacity: dict[str, str]) -> None: ...
    @property
    def consumes_counters(self) -> list[V1alpha3DeviceCounterConsumption]: ...
    @consumes_counters.setter
    def consumes_counters(self, consumes_counters: list[V1alpha3DeviceCounterConsumption]) -> None: ...
    @property
    def node_name(self) -> str: ...
    @node_name.setter
    def node_name(self, node_name: str) -> None: ...
    @property
    def node_selector(self) -> V1NodeSelector: ...
    @node_selector.setter
    def node_selector(self, node_selector: V1NodeSelector) -> None: ...
    @property
    def taints(self) -> list[V1alpha3DeviceTaint]: ...
    @taints.setter
    def taints(self, taints: list[V1alpha3DeviceTaint]) -> None: ...
