from kubernetes_asyncio.client.models import V1alpha1MigrationCondition
from typing import Any

class V1alpha1StorageVersionMigrationStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, conditions: list[V1alpha1MigrationCondition], resource_version: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def conditions(self) -> list[V1alpha1MigrationCondition]: ...
    @conditions.setter
    def conditions(self, conditions: list[V1alpha1MigrationCondition]) -> None: ...
    @property
    def resource_version(self) -> str: ...
    @resource_version.setter
    def resource_version(self, resource_version: str) -> None: ...
