from kubernetes_asyncio.client.models import V1alpha3DeviceSelector
from kubernetes_asyncio.client.models import V1alpha3DeviceSubRequest
from kubernetes_asyncio.client.models import V1alpha3DeviceToleration
from typing import Any

class V1alpha3DeviceRequest:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, admin_access: bool, allocation_mode: str, count: int, device_class_name: str, first_available: list[V1alpha3DeviceSubRequest], name: str, selectors: list[V1alpha3DeviceSelector], tolerations: list[V1alpha3DeviceToleration], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def admin_access(self) -> bool: ...
    @admin_access.setter
    def admin_access(self, admin_access: bool) -> None: ...
    @property
    def allocation_mode(self) -> str: ...
    @allocation_mode.setter
    def allocation_mode(self, allocation_mode: str) -> None: ...
    @property
    def count(self) -> int: ...
    @count.setter
    def count(self, count: int) -> None: ...
    @property
    def device_class_name(self) -> str: ...
    @device_class_name.setter
    def device_class_name(self, device_class_name: str) -> None: ...
    @property
    def first_available(self) -> list[V1alpha3DeviceSubRequest]: ...
    @first_available.setter
    def first_available(self, first_available: list[V1alpha3DeviceSubRequest]) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def selectors(self) -> list[V1alpha3DeviceSelector]: ...
    @selectors.setter
    def selectors(self, selectors: list[V1alpha3DeviceSelector]) -> None: ...
    @property
    def tolerations(self) -> list[V1alpha3DeviceToleration]: ...
    @tolerations.setter
    def tolerations(self, tolerations: list[V1alpha3DeviceToleration]) -> None: ...
