from kubernetes_asyncio.client.models import V1Condition
from kubernetes_asyncio.client.models import V1alpha3PoolStatus
from typing import Any

class V1alpha3ResourcePoolStatusRequestStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, conditions: list[V1Condition] | None = None, pool_count: int | None = None, pools: list[V1alpha3PoolStatus] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def conditions(self) -> list[V1Condition]: ...
    @conditions.setter
    def conditions(self, conditions: list[V1Condition]) -> None: ...
    @property
    def pool_count(self) -> int: ...
    @pool_count.setter
    def pool_count(self, pool_count: int) -> None: ...
    @property
    def pools(self) -> list[V1alpha3PoolStatus]: ...
    @pools.setter
    def pools(self, pools: list[V1alpha3PoolStatus]) -> None: ...
