from kubernetes_asyncio.client.models import V1alpha2PodGroupResourceClaim
from kubernetes_asyncio.client.models import V1alpha2PodGroupSchedulingConstraints
from kubernetes_asyncio.client.models import V1alpha2PodGroupSchedulingPolicy
from kubernetes_asyncio.client.models import V1alpha2PodGroupTemplateReference
from typing import Any

class V1alpha2PodGroupSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, disruption_mode: str | None = None, pod_group_template_ref: V1alpha2PodGroupTemplateReference | None = None, priority: int | None = None, priority_class_name: str | None = None, resource_claims: list[V1alpha2PodGroupResourceClaim] | None = None, scheduling_constraints: V1alpha2PodGroupSchedulingConstraints | None = None, scheduling_policy: V1alpha2PodGroupSchedulingPolicy | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def disruption_mode(self) -> str: ...
    @disruption_mode.setter
    def disruption_mode(self, disruption_mode: str) -> None: ...
    @property
    def pod_group_template_ref(self) -> V1alpha2PodGroupTemplateReference: ...
    @pod_group_template_ref.setter
    def pod_group_template_ref(self, pod_group_template_ref: V1alpha2PodGroupTemplateReference) -> None: ...
    @property
    def priority(self) -> int: ...
    @priority.setter
    def priority(self, priority: int) -> None: ...
    @property
    def priority_class_name(self) -> str: ...
    @priority_class_name.setter
    def priority_class_name(self, priority_class_name: str) -> None: ...
    @property
    def resource_claims(self) -> list[V1alpha2PodGroupResourceClaim]: ...
    @resource_claims.setter
    def resource_claims(self, resource_claims: list[V1alpha2PodGroupResourceClaim]) -> None: ...
    @property
    def scheduling_constraints(self) -> V1alpha2PodGroupSchedulingConstraints: ...
    @scheduling_constraints.setter
    def scheduling_constraints(self, scheduling_constraints: V1alpha2PodGroupSchedulingConstraints) -> None: ...
    @property
    def scheduling_policy(self) -> V1alpha2PodGroupSchedulingPolicy: ...
    @scheduling_policy.setter
    def scheduling_policy(self, scheduling_policy: V1alpha2PodGroupSchedulingPolicy) -> None: ...
