from kubernetes_asyncio.client.models import V1alpha3DeviceClassConfiguration
from kubernetes_asyncio.client.models import V1alpha3DeviceSelector
from typing import Any

class V1alpha3DeviceClassSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, config: list[V1alpha3DeviceClassConfiguration], selectors: list[V1alpha3DeviceSelector], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def config(self) -> list[V1alpha3DeviceClassConfiguration]: ...
    @config.setter
    def config(self, config: list[V1alpha3DeviceClassConfiguration]) -> None: ...
    @property
    def selectors(self) -> list[V1alpha3DeviceSelector]: ...
    @selectors.setter
    def selectors(self, selectors: list[V1alpha3DeviceSelector]) -> None: ...
