from kubernetes_asyncio.client.models import V1alpha2WorkloadPodGroupTemplateReference
from typing import Any

class V1alpha2PodGroupTemplateReference:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, workload: V1alpha2WorkloadPodGroupTemplateReference | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def workload(self) -> V1alpha2WorkloadPodGroupTemplateReference: ...
    @workload.setter
    def workload(self, workload: V1alpha2WorkloadPodGroupTemplateReference) -> None: ...
