from kubernetes_asyncio.client.models import V1Condition
from kubernetes_asyncio.client.models import V1alpha2PodGroupResourceClaimStatus
from typing import Any

class V1alpha2PodGroupStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, conditions: list[V1Condition] | None = None, resource_claim_statuses: list[V1alpha2PodGroupResourceClaimStatus] | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def conditions(self) -> list[V1Condition]: ...
    @conditions.setter
    def conditions(self, conditions: list[V1Condition]) -> None: ...
    @property
    def resource_claim_statuses(self) -> list[V1alpha2PodGroupResourceClaimStatus]: ...
    @resource_claim_statuses.setter
    def resource_claim_statuses(self, resource_claim_statuses: list[V1alpha2PodGroupResourceClaimStatus]) -> None: ...
