from typing import Any

class V1alpha3PoolStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, allocated_devices: int | None = None, available_devices: int | None = None, driver: str | None = None, generation: int | None = None, node_name: str | None = None, pool_name: str | None = None, resource_slice_count: int | None = None, total_devices: int | None = None, unavailable_devices: int | None = None, validation_error: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def allocated_devices(self) -> int: ...
    @allocated_devices.setter
    def allocated_devices(self, allocated_devices: int) -> None: ...
    @property
    def available_devices(self) -> int: ...
    @available_devices.setter
    def available_devices(self, available_devices: int) -> None: ...
    @property
    def driver(self) -> str: ...
    @driver.setter
    def driver(self, driver: str) -> None: ...
    @property
    def generation(self) -> int: ...
    @generation.setter
    def generation(self, generation: int) -> None: ...
    @property
    def node_name(self) -> str: ...
    @node_name.setter
    def node_name(self, node_name: str) -> None: ...
    @property
    def pool_name(self) -> str: ...
    @pool_name.setter
    def pool_name(self, pool_name: str) -> None: ...
    @property
    def resource_slice_count(self) -> int: ...
    @resource_slice_count.setter
    def resource_slice_count(self, resource_slice_count: int) -> None: ...
    @property
    def total_devices(self) -> int: ...
    @total_devices.setter
    def total_devices(self, total_devices: int) -> None: ...
    @property
    def unavailable_devices(self) -> int: ...
    @unavailable_devices.setter
    def unavailable_devices(self, unavailable_devices: int) -> None: ...
    @property
    def validation_error(self) -> str: ...
    @validation_error.setter
    def validation_error(self, validation_error: str) -> None: ...
