from typing import Any

class V1alpha3ResourcePool:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, generation: int, name: str, resource_slice_count: int, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def generation(self) -> int: ...
    @generation.setter
    def generation(self, generation: int) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def resource_slice_count(self) -> int: ...
    @resource_slice_count.setter
    def resource_slice_count(self, resource_slice_count: int) -> None: ...
