from typing import Any

class V1alpha3ResourcePoolStatusRequestSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, driver: str | None = None, limit: int | None = None, pool_name: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def driver(self) -> str: ...
    @driver.setter
    def driver(self, driver: str) -> None: ...
    @property
    def limit(self) -> int: ...
    @limit.setter
    def limit(self, limit: int) -> None: ...
    @property
    def pool_name(self) -> str: ...
    @pool_name.setter
    def pool_name(self, pool_name: str) -> None: ...
