from typing import Any

class V1beta2DeviceCapacity:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, value: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...
