from kubernetes_asyncio.client.models import V1beta1MatchResources
from kubernetes_asyncio.client.models import V1beta1ParamRef
from typing import Any

class V1beta1ValidatingAdmissionPolicyBindingSpec:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, match_resources: V1beta1MatchResources, param_ref: V1beta1ParamRef, policy_name: str, validation_actions: list[str], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def match_resources(self) -> V1beta1MatchResources: ...
    @match_resources.setter
    def match_resources(self, match_resources: V1beta1MatchResources) -> None: ...
    @property
    def param_ref(self) -> V1beta1ParamRef: ...
    @param_ref.setter
    def param_ref(self, param_ref: V1beta1ParamRef) -> None: ...
    @property
    def policy_name(self) -> str: ...
    @policy_name.setter
    def policy_name(self, policy_name: str) -> None: ...
    @property
    def validation_actions(self) -> list[str]: ...
    @validation_actions.setter
    def validation_actions(self, validation_actions: list[str]) -> None: ...
