from typing import Any

class V1beta2ResourceClaimConsumerReference:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_group: str, name: str, resource: str, uid: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_group(self) -> str: ...
    @api_group.setter
    def api_group(self, api_group: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def resource(self) -> str: ...
    @resource.setter
    def resource(self, resource: str) -> None: ...
    @property
    def uid(self) -> str: ...
    @uid.setter
    def uid(self, uid: str) -> None: ...
