from typing import Any

class V1beta1Validation:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, expression: str, message: str, message_expression: str, reason: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def expression(self) -> str: ...
    @expression.setter
    def expression(self, expression: str) -> None: ...
    @property
    def message(self) -> str: ...
    @message.setter
    def message(self, message: str) -> None: ...
    @property
    def message_expression(self) -> str: ...
    @message_expression.setter
    def message_expression(self, message_expression: str) -> None: ...
    @property
    def reason(self) -> str: ...
    @reason.setter
    def reason(self, reason: str) -> None: ...
