from typing import Any

class V1beta1Variable:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, expression: str, name: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def expression(self) -> str: ...
    @expression.setter
    def expression(self, expression: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
