from kubernetes_asyncio.client.models import V1beta2Counter
from typing import Any

class V1beta2CounterSet:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, counters: dict[str, V1beta2Counter], name: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def counters(self) -> dict[str, V1beta2Counter]: ...
    @counters.setter
    def counters(self, counters: dict[str, V1beta2Counter]) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
