from typing import Any

class V1beta1DeviceConstraint:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, match_attribute: str, requests: list[str], local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def match_attribute(self) -> str: ...
    @match_attribute.setter
    def match_attribute(self, match_attribute: str) -> None: ...
    @property
    def requests(self) -> list[str]: ...
    @requests.setter
    def requests(self, requests: list[str]) -> None: ...
