from kubernetes_asyncio.client.models import V1ListMeta
from kubernetes_asyncio.client.models import V1beta1ValidatingAdmissionPolicyBinding
from typing import Any

class V1beta1ValidatingAdmissionPolicyBindingList:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, api_version: str, items: list[V1beta1ValidatingAdmissionPolicyBinding], kind: str, metadata: V1ListMeta, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def api_version(self) -> str: ...
    @api_version.setter
    def api_version(self, api_version: str) -> None: ...
    @property
    def items(self) -> list[V1beta1ValidatingAdmissionPolicyBinding]: ...
    @items.setter
    def items(self, items: list[V1beta1ValidatingAdmissionPolicyBinding]) -> None: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    @property
    def metadata(self) -> V1ListMeta: ...
    @metadata.setter
    def metadata(self, metadata: V1ListMeta) -> None: ...
