from typing import Any

class V1beta1NodeAllocatableResourceMapping:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, allocation_multiplier: str | None = None, capacity_key: str | None = None, local_vars_configuration: Any | None = None) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize: bool = False) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def allocation_multiplier(self) -> str: ...
    @allocation_multiplier.setter
    def allocation_multiplier(self, allocation_multiplier: str) -> None: ...
    @property
    def capacity_key(self) -> str: ...
    @capacity_key.setter
    def capacity_key(self, capacity_key: str) -> None: ...
