from kubernetes_asyncio.client.models import V1beta1OpaqueDeviceConfiguration
from typing import Any

class V1beta1DeviceAllocationConfiguration:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, opaque: V1beta1OpaqueDeviceConfiguration, requests: list[str], source: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def opaque(self) -> V1beta1OpaqueDeviceConfiguration: ...
    @opaque.setter
    def opaque(self, opaque: V1beta1OpaqueDeviceConfiguration) -> None: ...
    @property
    def requests(self) -> list[str]: ...
    @requests.setter
    def requests(self, requests: list[str]) -> None: ...
    @property
    def source(self) -> str: ...
    @source.setter
    def source(self, source: str) -> None: ...
