from kubernetes_asyncio.client.models import V1LabelSelector
from typing import Any

class V2MetricIdentifier:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, name: str, selector: V1LabelSelector, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def selector(self) -> V1LabelSelector: ...
    @selector.setter
    def selector(self, selector: V1LabelSelector) -> None: ...
