from kubernetes_asyncio.client.models import V2CrossVersionObjectReference
from kubernetes_asyncio.client.models import V2MetricIdentifier
from kubernetes_asyncio.client.models import V2MetricValueStatus
from typing import Any

class V2ObjectMetricStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, current: V2MetricValueStatus, described_object: V2CrossVersionObjectReference, metric: V2MetricIdentifier, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def current(self) -> V2MetricValueStatus: ...
    @current.setter
    def current(self, current: V2MetricValueStatus) -> None: ...
    @property
    def described_object(self) -> V2CrossVersionObjectReference: ...
    @described_object.setter
    def described_object(self, described_object: V2CrossVersionObjectReference) -> None: ...
    @property
    def metric(self) -> V2MetricIdentifier: ...
    @metric.setter
    def metric(self, metric: V2MetricIdentifier) -> None: ...
