from kubernetes_asyncio.client.models import V2MetricValueStatus
from typing import Any

class V2ResourceMetricStatus:
    def __eq__(self, other: Any) -> bool: ...
    def __init__(self, current: V2MetricValueStatus, name: str, local_vars_configuration: Any) -> None: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dict(self, serialize) -> dict[str, Any]: ...
    def to_str(self) -> str: ...
    @property
    def current(self) -> V2MetricValueStatus: ...
    @current.setter
    def current(self, current: V2MetricValueStatus) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
