from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1alpha1MutatingAdmissionPolicy
from kubernetes_asyncio.client.models import V1alpha1MutatingAdmissionPolicyBinding
from kubernetes_asyncio.client.models import V1alpha1MutatingAdmissionPolicyBindingList
from kubernetes_asyncio.client.models import V1alpha1MutatingAdmissionPolicyList
from multidict import CIMultiDictProxy
from typing import Any

class AdmissionregistrationV1alpha1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_mutating_admission_policy(self, body: V1alpha1MutatingAdmissionPolicy, kwargs: Any) -> V1alpha1MutatingAdmissionPolicy: ...
    def create_mutating_admission_policy_binding(self, body: V1alpha1MutatingAdmissionPolicyBinding, kwargs: Any) -> V1alpha1MutatingAdmissionPolicyBinding: ...
    def create_mutating_admission_policy_binding_with_http_info(self, body: V1alpha1MutatingAdmissionPolicyBinding, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicyBinding, int, CIMultiDictProxy]: ...
    def create_mutating_admission_policy_with_http_info(self, body: V1alpha1MutatingAdmissionPolicy, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicy, int, CIMultiDictProxy]: ...
    def delete_collection_mutating_admission_policy(self, kwargs: Any) -> V1Status: ...
    def delete_collection_mutating_admission_policy_binding(self, kwargs: Any) -> V1Status: ...
    def delete_collection_mutating_admission_policy_binding_with_http_info(self, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_collection_mutating_admission_policy_with_http_info(self, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_mutating_admission_policy(self, name: str, kwargs: Any) -> V1Status: ...
    def delete_mutating_admission_policy_binding(self, name: str, kwargs: Any) -> V1Status: ...
    def delete_mutating_admission_policy_binding_with_http_info(self, name: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_mutating_admission_policy_with_http_info(self, name: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def get_api_resources(self, kwargs: Any) -> V1APIResourceList: ...
    def get_api_resources_with_http_info(self, kwargs: Any) -> tuple[V1APIResourceList, int, CIMultiDictProxy]: ...
    def list_mutating_admission_policy(self, kwargs: Any) -> V1alpha1MutatingAdmissionPolicyList: ...
    def list_mutating_admission_policy_binding(self, kwargs: Any) -> V1alpha1MutatingAdmissionPolicyBindingList: ...
    def list_mutating_admission_policy_binding_with_http_info(self, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicyBindingList, int, CIMultiDictProxy]: ...
    def list_mutating_admission_policy_with_http_info(self, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicyList, int, CIMultiDictProxy]: ...
    def patch_mutating_admission_policy(self, name: str, body: Any, kwargs: Any) -> V1alpha1MutatingAdmissionPolicy: ...
    def patch_mutating_admission_policy_binding(self, name: str, body: Any, kwargs: Any) -> V1alpha1MutatingAdmissionPolicyBinding: ...
    def patch_mutating_admission_policy_binding_with_http_info(self, name: str, body: Any, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicyBinding, int, CIMultiDictProxy]: ...
    def patch_mutating_admission_policy_with_http_info(self, name: str, body: Any, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicy, int, CIMultiDictProxy]: ...
    def read_mutating_admission_policy(self, name: str, kwargs: Any) -> V1alpha1MutatingAdmissionPolicy: ...
    def read_mutating_admission_policy_binding(self, name: str, kwargs: Any) -> V1alpha1MutatingAdmissionPolicyBinding: ...
    def read_mutating_admission_policy_binding_with_http_info(self, name: str, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicyBinding, int, CIMultiDictProxy]: ...
    def read_mutating_admission_policy_with_http_info(self, name: str, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicy, int, CIMultiDictProxy]: ...
    def replace_mutating_admission_policy(self, name: str, body: V1alpha1MutatingAdmissionPolicy, kwargs: Any) -> V1alpha1MutatingAdmissionPolicy: ...
    def replace_mutating_admission_policy_binding(self, name: str, body: V1alpha1MutatingAdmissionPolicyBinding, kwargs: Any) -> V1alpha1MutatingAdmissionPolicyBinding: ...
    def replace_mutating_admission_policy_binding_with_http_info(self, name: str, body: V1alpha1MutatingAdmissionPolicyBinding, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicyBinding, int, CIMultiDictProxy]: ...
    def replace_mutating_admission_policy_with_http_info(self, name: str, body: V1alpha1MutatingAdmissionPolicy, kwargs: Any) -> tuple[V1alpha1MutatingAdmissionPolicy, int, CIMultiDictProxy]: ...
