from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1beta1ValidatingAdmissionPolicy
from kubernetes_asyncio.client.models import V1beta1ValidatingAdmissionPolicyBinding
from kubernetes_asyncio.client.models import V1beta1ValidatingAdmissionPolicyBindingList
from kubernetes_asyncio.client.models import V1beta1ValidatingAdmissionPolicyList
from multidict import CIMultiDictProxy
from typing import Any

class AdmissionregistrationV1beta1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_validating_admission_policy(self, body: V1beta1ValidatingAdmissionPolicy, kwargs: Any) -> V1beta1ValidatingAdmissionPolicy: ...
    def create_validating_admission_policy_binding(self, body: V1beta1ValidatingAdmissionPolicyBinding, kwargs: Any) -> V1beta1ValidatingAdmissionPolicyBinding: ...
    def create_validating_admission_policy_binding_with_http_info(self, body: V1beta1ValidatingAdmissionPolicyBinding, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicyBinding, int, CIMultiDictProxy]: ...
    def create_validating_admission_policy_with_http_info(self, body: V1beta1ValidatingAdmissionPolicy, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicy, int, CIMultiDictProxy]: ...
    def delete_collection_validating_admission_policy(self, kwargs: Any) -> V1Status: ...
    def delete_collection_validating_admission_policy_binding(self, kwargs: Any) -> V1Status: ...
    def delete_collection_validating_admission_policy_binding_with_http_info(self, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_collection_validating_admission_policy_with_http_info(self, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_validating_admission_policy(self, name: str, kwargs: Any) -> V1Status: ...
    def delete_validating_admission_policy_binding(self, name: str, kwargs: Any) -> V1Status: ...
    def delete_validating_admission_policy_binding_with_http_info(self, name: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_validating_admission_policy_with_http_info(self, name: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def get_api_resources(self, kwargs: Any) -> V1APIResourceList: ...
    def get_api_resources_with_http_info(self, kwargs: Any) -> tuple[V1APIResourceList, int, CIMultiDictProxy]: ...
    def list_validating_admission_policy(self, kwargs: Any) -> V1beta1ValidatingAdmissionPolicyList: ...
    def list_validating_admission_policy_binding(self, kwargs: Any) -> V1beta1ValidatingAdmissionPolicyBindingList: ...
    def list_validating_admission_policy_binding_with_http_info(self, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicyBindingList, int, CIMultiDictProxy]: ...
    def list_validating_admission_policy_with_http_info(self, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicyList, int, CIMultiDictProxy]: ...
    def patch_validating_admission_policy(self, name: str, body: Any, kwargs: Any) -> V1beta1ValidatingAdmissionPolicy: ...
    def patch_validating_admission_policy_binding(self, name: str, body: Any, kwargs: Any) -> V1beta1ValidatingAdmissionPolicyBinding: ...
    def patch_validating_admission_policy_binding_with_http_info(self, name: str, body: Any, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicyBinding, int, CIMultiDictProxy]: ...
    def patch_validating_admission_policy_status(self, name: str, body: Any, kwargs: Any) -> V1beta1ValidatingAdmissionPolicy: ...
    def patch_validating_admission_policy_status_with_http_info(self, name: str, body: Any, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicy, int, CIMultiDictProxy]: ...
    def patch_validating_admission_policy_with_http_info(self, name: str, body: Any, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicy, int, CIMultiDictProxy]: ...
    def read_validating_admission_policy(self, name: str, kwargs: Any) -> V1beta1ValidatingAdmissionPolicy: ...
    def read_validating_admission_policy_binding(self, name: str, kwargs: Any) -> V1beta1ValidatingAdmissionPolicyBinding: ...
    def read_validating_admission_policy_binding_with_http_info(self, name: str, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicyBinding, int, CIMultiDictProxy]: ...
    def read_validating_admission_policy_status(self, name: str, kwargs: Any) -> V1beta1ValidatingAdmissionPolicy: ...
    def read_validating_admission_policy_status_with_http_info(self, name: str, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicy, int, CIMultiDictProxy]: ...
    def read_validating_admission_policy_with_http_info(self, name: str, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicy, int, CIMultiDictProxy]: ...
    def replace_validating_admission_policy(self, name: str, body: V1beta1ValidatingAdmissionPolicy, kwargs: Any) -> V1beta1ValidatingAdmissionPolicy: ...
    def replace_validating_admission_policy_binding(self, name: str, body: V1beta1ValidatingAdmissionPolicyBinding, kwargs: Any) -> V1beta1ValidatingAdmissionPolicyBinding: ...
    def replace_validating_admission_policy_binding_with_http_info(self, name: str, body: V1beta1ValidatingAdmissionPolicyBinding, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicyBinding, int, CIMultiDictProxy]: ...
    def replace_validating_admission_policy_status(self, name: str, body: V1beta1ValidatingAdmissionPolicy, kwargs: Any) -> V1beta1ValidatingAdmissionPolicy: ...
    def replace_validating_admission_policy_status_with_http_info(self, name: str, body: V1beta1ValidatingAdmissionPolicy, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicy, int, CIMultiDictProxy]: ...
    def replace_validating_admission_policy_with_http_info(self, name: str, body: V1beta1ValidatingAdmissionPolicy, kwargs: Any) -> tuple[V1beta1ValidatingAdmissionPolicy, int, CIMultiDictProxy]: ...
