from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1SelfSubjectReview
from kubernetes_asyncio.client.models import V1TokenReview
from multidict import CIMultiDictProxy
from typing import Any

class AuthenticationV1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_self_subject_review(self, body: V1SelfSubjectReview, kwargs: Any) -> V1SelfSubjectReview: ...
    def create_self_subject_review_with_http_info(self, body: V1SelfSubjectReview, kwargs: Any) -> tuple[V1SelfSubjectReview, int, CIMultiDictProxy]: ...
    def create_token_review(self, body: V1TokenReview, kwargs: Any) -> V1TokenReview: ...
    def create_token_review_with_http_info(self, body: V1TokenReview, kwargs: Any) -> tuple[V1TokenReview, int, CIMultiDictProxy]: ...
    def get_api_resources(self, kwargs: Any) -> V1APIResourceList: ...
    def get_api_resources_with_http_info(self, kwargs: Any) -> tuple[V1APIResourceList, int, CIMultiDictProxy]: ...
