from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V2HorizontalPodAutoscaler
from kubernetes_asyncio.client.models import V2HorizontalPodAutoscalerList
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class AutoscalingV2Api:
    def __init__(self, api_client: ApiClient | None = None) -> None: ...
    def create_namespaced_horizontal_pod_autoscaler(self, namespace: str, body: V2HorizontalPodAutoscaler, **kwargs: Any) -> Awaitable[V2HorizontalPodAutoscaler]: ...
    def create_namespaced_horizontal_pod_autoscaler_with_http_info(self, namespace: str, body: V2HorizontalPodAutoscaler, **kwargs: Any) -> Awaitable[tuple[V2HorizontalPodAutoscaler, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_horizontal_pod_autoscaler(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_horizontal_pod_autoscaler_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_namespaced_horizontal_pod_autoscaler(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_namespaced_horizontal_pod_autoscaler_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_horizontal_pod_autoscaler_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V2HorizontalPodAutoscalerList]: ...
    def list_horizontal_pod_autoscaler_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V2HorizontalPodAutoscalerList, int, CIMultiDictProxy]]: ...
    def list_namespaced_horizontal_pod_autoscaler(self, namespace: str, **kwargs: Any) -> Awaitable[V2HorizontalPodAutoscalerList]: ...
    def list_namespaced_horizontal_pod_autoscaler_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V2HorizontalPodAutoscalerList, int, CIMultiDictProxy]]: ...
    def patch_namespaced_horizontal_pod_autoscaler(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V2HorizontalPodAutoscaler]: ...
    def patch_namespaced_horizontal_pod_autoscaler_status(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V2HorizontalPodAutoscaler]: ...
    def patch_namespaced_horizontal_pod_autoscaler_status_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V2HorizontalPodAutoscaler, int, CIMultiDictProxy]]: ...
    def patch_namespaced_horizontal_pod_autoscaler_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V2HorizontalPodAutoscaler, int, CIMultiDictProxy]]: ...
    def read_namespaced_horizontal_pod_autoscaler(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V2HorizontalPodAutoscaler]: ...
    def read_namespaced_horizontal_pod_autoscaler_status(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V2HorizontalPodAutoscaler]: ...
    def read_namespaced_horizontal_pod_autoscaler_status_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V2HorizontalPodAutoscaler, int, CIMultiDictProxy]]: ...
    def read_namespaced_horizontal_pod_autoscaler_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V2HorizontalPodAutoscaler, int, CIMultiDictProxy]]: ...
    def replace_namespaced_horizontal_pod_autoscaler(self, name: str, namespace: str, body: V2HorizontalPodAutoscaler, **kwargs: Any) -> Awaitable[V2HorizontalPodAutoscaler]: ...
    def replace_namespaced_horizontal_pod_autoscaler_status(self, name: str, namespace: str, body: V2HorizontalPodAutoscaler, **kwargs: Any) -> Awaitable[V2HorizontalPodAutoscaler]: ...
    def replace_namespaced_horizontal_pod_autoscaler_status_with_http_info(self, name: str, namespace: str, body: V2HorizontalPodAutoscaler, **kwargs: Any) -> Awaitable[tuple[V2HorizontalPodAutoscaler, int, CIMultiDictProxy]]: ...
    def replace_namespaced_horizontal_pod_autoscaler_with_http_info(self, name: str, namespace: str, body: V2HorizontalPodAutoscaler, **kwargs: Any) -> Awaitable[tuple[V2HorizontalPodAutoscaler, int, CIMultiDictProxy]]: ...
