from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1alpha1ClusterTrustBundle
from kubernetes_asyncio.client.models import V1alpha1ClusterTrustBundleList
from kubernetes_asyncio.client.models import V1alpha1PodCertificateRequest
from kubernetes_asyncio.client.models import V1alpha1PodCertificateRequestList
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class CertificatesV1alpha1Api:
    def __init__(self, api_client: ApiClient | None = None) -> None: ...
    def create_cluster_trust_bundle(self, body: V1alpha1ClusterTrustBundle, **kwargs: Any) -> Awaitable[V1alpha1ClusterTrustBundle]: ...
    def create_cluster_trust_bundle_with_http_info(self, body: V1alpha1ClusterTrustBundle, **kwargs: Any) -> Awaitable[tuple[V1alpha1ClusterTrustBundle, int, CIMultiDictProxy]]: ...
    def create_namespaced_pod_certificate_request(self, namespace: str, body: V1alpha1PodCertificateRequest, **kwargs: Any) -> Awaitable[V1alpha1PodCertificateRequest]: ...
    def create_namespaced_pod_certificate_request_with_http_info(self, namespace: str, body: V1alpha1PodCertificateRequest, **kwargs: Any) -> Awaitable[tuple[V1alpha1PodCertificateRequest, int, CIMultiDictProxy]]: ...
    def delete_cluster_trust_bundle(self, name: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_cluster_trust_bundle_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_cluster_trust_bundle(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_cluster_trust_bundle_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_pod_certificate_request(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_pod_certificate_request_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_namespaced_pod_certificate_request(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_namespaced_pod_certificate_request_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_cluster_trust_bundle(self, **kwargs: Any) -> Awaitable[V1alpha1ClusterTrustBundleList]: ...
    def list_cluster_trust_bundle_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1alpha1ClusterTrustBundleList, int, CIMultiDictProxy]]: ...
    def list_namespaced_pod_certificate_request(self, namespace: str, **kwargs: Any) -> Awaitable[V1alpha1PodCertificateRequestList]: ...
    def list_namespaced_pod_certificate_request_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha1PodCertificateRequestList, int, CIMultiDictProxy]]: ...
    def list_pod_certificate_request_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V1alpha1PodCertificateRequestList]: ...
    def list_pod_certificate_request_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1alpha1PodCertificateRequestList, int, CIMultiDictProxy]]: ...
    def patch_cluster_trust_bundle(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha1ClusterTrustBundle]: ...
    def patch_cluster_trust_bundle_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha1ClusterTrustBundle, int, CIMultiDictProxy]]: ...
    def patch_namespaced_pod_certificate_request(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha1PodCertificateRequest]: ...
    def patch_namespaced_pod_certificate_request_status(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha1PodCertificateRequest]: ...
    def patch_namespaced_pod_certificate_request_status_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha1PodCertificateRequest, int, CIMultiDictProxy]]: ...
    def patch_namespaced_pod_certificate_request_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha1PodCertificateRequest, int, CIMultiDictProxy]]: ...
    def read_cluster_trust_bundle(self, name: str, **kwargs: Any) -> Awaitable[V1alpha1ClusterTrustBundle]: ...
    def read_cluster_trust_bundle_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1alpha1ClusterTrustBundle, int, CIMultiDictProxy]]: ...
    def read_namespaced_pod_certificate_request(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1alpha1PodCertificateRequest]: ...
    def read_namespaced_pod_certificate_request_status(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1alpha1PodCertificateRequest]: ...
    def read_namespaced_pod_certificate_request_status_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha1PodCertificateRequest, int, CIMultiDictProxy]]: ...
    def read_namespaced_pod_certificate_request_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha1PodCertificateRequest, int, CIMultiDictProxy]]: ...
    def replace_cluster_trust_bundle(self, name: str, body: V1alpha1ClusterTrustBundle, **kwargs: Any) -> Awaitable[V1alpha1ClusterTrustBundle]: ...
    def replace_cluster_trust_bundle_with_http_info(self, name: str, body: V1alpha1ClusterTrustBundle, **kwargs: Any) -> Awaitable[tuple[V1alpha1ClusterTrustBundle, int, CIMultiDictProxy]]: ...
    def replace_namespaced_pod_certificate_request(self, name: str, namespace: str, body: V1alpha1PodCertificateRequest, **kwargs: Any) -> Awaitable[V1alpha1PodCertificateRequest]: ...
    def replace_namespaced_pod_certificate_request_status(self, name: str, namespace: str, body: V1alpha1PodCertificateRequest, **kwargs: Any) -> Awaitable[V1alpha1PodCertificateRequest]: ...
    def replace_namespaced_pod_certificate_request_status_with_http_info(self, name: str, namespace: str, body: V1alpha1PodCertificateRequest, **kwargs: Any) -> Awaitable[tuple[V1alpha1PodCertificateRequest, int, CIMultiDictProxy]]: ...
    def replace_namespaced_pod_certificate_request_with_http_info(self, name: str, namespace: str, body: V1alpha1PodCertificateRequest, **kwargs: Any) -> Awaitable[tuple[V1alpha1PodCertificateRequest, int, CIMultiDictProxy]]: ...
