from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1beta1ClusterTrustBundle
from kubernetes_asyncio.client.models import V1beta1ClusterTrustBundleList
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class CertificatesV1beta1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_cluster_trust_bundle(self, body: V1beta1ClusterTrustBundle, **kwargs: Any) -> Awaitable[V1beta1ClusterTrustBundle]: ...
    def create_cluster_trust_bundle_with_http_info(self, body: V1beta1ClusterTrustBundle, **kwargs: Any) -> Awaitable[tuple[V1beta1ClusterTrustBundle, int, CIMultiDictProxy]]: ...
    def delete_cluster_trust_bundle(self, name: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_cluster_trust_bundle_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_cluster_trust_bundle(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_cluster_trust_bundle_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_cluster_trust_bundle(self, **kwargs: Any) -> Awaitable[V1beta1ClusterTrustBundleList]: ...
    def list_cluster_trust_bundle_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1beta1ClusterTrustBundleList, int, CIMultiDictProxy]]: ...
    def patch_cluster_trust_bundle(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1beta1ClusterTrustBundle]: ...
    def patch_cluster_trust_bundle_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1beta1ClusterTrustBundle, int, CIMultiDictProxy]]: ...
    def read_cluster_trust_bundle(self, name: str, **kwargs: Any) -> Awaitable[V1beta1ClusterTrustBundle]: ...
    def read_cluster_trust_bundle_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ClusterTrustBundle, int, CIMultiDictProxy]]: ...
    def replace_cluster_trust_bundle(self, name: str, body: V1beta1ClusterTrustBundle, **kwargs: Any) -> Awaitable[V1beta1ClusterTrustBundle]: ...
    def replace_cluster_trust_bundle_with_http_info(self, name: str, body: V1beta1ClusterTrustBundle, **kwargs: Any) -> Awaitable[tuple[V1beta1ClusterTrustBundle, int, CIMultiDictProxy]]: ...
