from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Lease
from kubernetes_asyncio.client.models import V1LeaseList
from kubernetes_asyncio.client.models import V1Status
from multidict import CIMultiDictProxy
from typing import Any

class CoordinationV1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_namespaced_lease(self, namespace: str, body: V1Lease, kwargs: Any) -> V1Lease: ...
    def create_namespaced_lease_with_http_info(self, namespace: str, body: V1Lease, kwargs: Any) -> tuple[V1Lease, int, CIMultiDictProxy]: ...
    def delete_collection_namespaced_lease(self, namespace: str, kwargs: Any) -> V1Status: ...
    def delete_collection_namespaced_lease_with_http_info(self, namespace: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_namespaced_lease(self, name: str, namespace: str, kwargs: Any) -> V1Status: ...
    def delete_namespaced_lease_with_http_info(self, name: str, namespace: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def get_api_resources(self, kwargs: Any) -> V1APIResourceList: ...
    def get_api_resources_with_http_info(self, kwargs: Any) -> tuple[V1APIResourceList, int, CIMultiDictProxy]: ...
    def list_lease_for_all_namespaces(self, kwargs: Any) -> V1LeaseList: ...
    def list_lease_for_all_namespaces_with_http_info(self, kwargs: Any) -> tuple[V1LeaseList, int, CIMultiDictProxy]: ...
    def list_namespaced_lease(self, namespace: str, kwargs: Any) -> V1LeaseList: ...
    def list_namespaced_lease_with_http_info(self, namespace: str, kwargs: Any) -> tuple[V1LeaseList, int, CIMultiDictProxy]: ...
    def patch_namespaced_lease(self, name: str, namespace: str, body: Any, kwargs: Any) -> V1Lease: ...
    def patch_namespaced_lease_with_http_info(self, name: str, namespace: str, body: Any, kwargs: Any) -> tuple[V1Lease, int, CIMultiDictProxy]: ...
    def read_namespaced_lease(self, name: str, namespace: str, kwargs: Any) -> V1Lease: ...
    def read_namespaced_lease_with_http_info(self, name: str, namespace: str, kwargs: Any) -> tuple[V1Lease, int, CIMultiDictProxy]: ...
    def replace_namespaced_lease(self, name: str, namespace: str, body: V1Lease, kwargs: Any) -> V1Lease: ...
    def replace_namespaced_lease_with_http_info(self, name: str, namespace: str, body: V1Lease, kwargs: Any) -> tuple[V1Lease, int, CIMultiDictProxy]: ...
