from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1alpha2LeaseCandidate
from kubernetes_asyncio.client.models import V1alpha2LeaseCandidateList
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class CoordinationV1alpha2Api:
    def __init__(self, api_client: ApiClient | None = None) -> None: ...
    def create_namespaced_lease_candidate(self, namespace: str, body: V1alpha2LeaseCandidate, **kwargs: Any) -> Awaitable[V1alpha2LeaseCandidate]: ...
    def create_namespaced_lease_candidate_with_http_info(self, namespace: str, body: V1alpha2LeaseCandidate, **kwargs: Any) -> Awaitable[tuple[V1alpha2LeaseCandidate, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_lease_candidate(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_lease_candidate_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_namespaced_lease_candidate(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_namespaced_lease_candidate_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_lease_candidate_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V1alpha2LeaseCandidateList]: ...
    def list_lease_candidate_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1alpha2LeaseCandidateList, int, CIMultiDictProxy]]: ...
    def list_namespaced_lease_candidate(self, namespace: str, **kwargs: Any) -> Awaitable[V1alpha2LeaseCandidateList]: ...
    def list_namespaced_lease_candidate_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha2LeaseCandidateList, int, CIMultiDictProxy]]: ...
    def patch_namespaced_lease_candidate(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha2LeaseCandidate]: ...
    def patch_namespaced_lease_candidate_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha2LeaseCandidate, int, CIMultiDictProxy]]: ...
    def read_namespaced_lease_candidate(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1alpha2LeaseCandidate]: ...
    def read_namespaced_lease_candidate_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha2LeaseCandidate, int, CIMultiDictProxy]]: ...
    def replace_namespaced_lease_candidate(self, name: str, namespace: str, body: V1alpha2LeaseCandidate, **kwargs: Any) -> Awaitable[V1alpha2LeaseCandidate]: ...
    def replace_namespaced_lease_candidate_with_http_info(self, name: str, namespace: str, body: V1alpha2LeaseCandidate, **kwargs: Any) -> Awaitable[tuple[V1alpha2LeaseCandidate, int, CIMultiDictProxy]]: ...
