from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1EndpointSlice
from kubernetes_asyncio.client.models import V1EndpointSliceList
from kubernetes_asyncio.client.models import V1Status
from multidict import CIMultiDictProxy
from typing import Any

class DiscoveryV1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_namespaced_endpoint_slice(self, namespace: str, body: V1EndpointSlice, kwargs: Any) -> V1EndpointSlice: ...
    def create_namespaced_endpoint_slice_with_http_info(self, namespace: str, body: V1EndpointSlice, kwargs: Any) -> tuple[V1EndpointSlice, int, CIMultiDictProxy]: ...
    def delete_collection_namespaced_endpoint_slice(self, namespace: str, kwargs: Any) -> V1Status: ...
    def delete_collection_namespaced_endpoint_slice_with_http_info(self, namespace: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_namespaced_endpoint_slice(self, name: str, namespace: str, kwargs: Any) -> V1Status: ...
    def delete_namespaced_endpoint_slice_with_http_info(self, name: str, namespace: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def get_api_resources(self, kwargs: Any) -> V1APIResourceList: ...
    def get_api_resources_with_http_info(self, kwargs: Any) -> tuple[V1APIResourceList, int, CIMultiDictProxy]: ...
    def list_endpoint_slice_for_all_namespaces(self, kwargs: Any) -> V1EndpointSliceList: ...
    def list_endpoint_slice_for_all_namespaces_with_http_info(self, kwargs: Any) -> tuple[V1EndpointSliceList, int, CIMultiDictProxy]: ...
    def list_namespaced_endpoint_slice(self, namespace: str, kwargs: Any) -> V1EndpointSliceList: ...
    def list_namespaced_endpoint_slice_with_http_info(self, namespace: str, kwargs: Any) -> tuple[V1EndpointSliceList, int, CIMultiDictProxy]: ...
    def patch_namespaced_endpoint_slice(self, name: str, namespace: str, body: Any, kwargs: Any) -> V1EndpointSlice: ...
    def patch_namespaced_endpoint_slice_with_http_info(self, name: str, namespace: str, body: Any, kwargs: Any) -> tuple[V1EndpointSlice, int, CIMultiDictProxy]: ...
    def read_namespaced_endpoint_slice(self, name: str, namespace: str, kwargs: Any) -> V1EndpointSlice: ...
    def read_namespaced_endpoint_slice_with_http_info(self, name: str, namespace: str, kwargs: Any) -> tuple[V1EndpointSlice, int, CIMultiDictProxy]: ...
    def replace_namespaced_endpoint_slice(self, name: str, namespace: str, body: V1EndpointSlice, kwargs: Any) -> V1EndpointSlice: ...
    def replace_namespaced_endpoint_slice_with_http_info(self, name: str, namespace: str, body: V1EndpointSlice, kwargs: Any) -> tuple[V1EndpointSlice, int, CIMultiDictProxy]: ...
