from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1alpha1StorageVersion
from kubernetes_asyncio.client.models import V1alpha1StorageVersionList
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class InternalApiserverV1alpha1Api:
    def __init__(self, api_client: ApiClient | None = None) -> None: ...
    def create_storage_version(self, body: V1alpha1StorageVersion, **kwargs: Any) -> Awaitable[V1alpha1StorageVersion]: ...
    def create_storage_version_with_http_info(self, body: V1alpha1StorageVersion, **kwargs: Any) -> Awaitable[tuple[V1alpha1StorageVersion, int, CIMultiDictProxy]]: ...
    def delete_collection_storage_version(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_storage_version_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_storage_version(self, name: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_storage_version_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_storage_version(self, **kwargs: Any) -> Awaitable[V1alpha1StorageVersionList]: ...
    def list_storage_version_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1alpha1StorageVersionList, int, CIMultiDictProxy]]: ...
    def patch_storage_version(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha1StorageVersion]: ...
    def patch_storage_version_status(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha1StorageVersion]: ...
    def patch_storage_version_status_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha1StorageVersion, int, CIMultiDictProxy]]: ...
    def patch_storage_version_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha1StorageVersion, int, CIMultiDictProxy]]: ...
    def read_storage_version(self, name: str, **kwargs: Any) -> Awaitable[V1alpha1StorageVersion]: ...
    def read_storage_version_status(self, name: str, **kwargs: Any) -> Awaitable[V1alpha1StorageVersion]: ...
    def read_storage_version_status_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1alpha1StorageVersion, int, CIMultiDictProxy]]: ...
    def read_storage_version_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1alpha1StorageVersion, int, CIMultiDictProxy]]: ...
    def replace_storage_version(self, name: str, body: V1alpha1StorageVersion, **kwargs: Any) -> Awaitable[V1alpha1StorageVersion]: ...
    def replace_storage_version_status(self, name: str, body: V1alpha1StorageVersion, **kwargs: Any) -> Awaitable[V1alpha1StorageVersion]: ...
    def replace_storage_version_status_with_http_info(self, name: str, body: V1alpha1StorageVersion, **kwargs: Any) -> Awaitable[tuple[V1alpha1StorageVersion, int, CIMultiDictProxy]]: ...
    def replace_storage_version_with_http_info(self, name: str, body: V1alpha1StorageVersion, **kwargs: Any) -> Awaitable[tuple[V1alpha1StorageVersion, int, CIMultiDictProxy]]: ...
