from kubernetes_asyncio.client.api_client import ApiClient
from multidict import CIMultiDictProxy
from typing import Any

class OpenidApi:
    def __init__(self, api_client: ApiClient) -> None: ...
    def get_service_account_issuer_open_id_keyset(self, kwargs: Any) -> str: ...
    def get_service_account_issuer_open_id_keyset_with_http_info(self, kwargs: Any) -> tuple[str, int, CIMultiDictProxy]: ...
