from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1PodDisruptionBudget
from kubernetes_asyncio.client.models import V1PodDisruptionBudgetList
from kubernetes_asyncio.client.models import V1Status
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class PolicyV1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_namespaced_pod_disruption_budget(self, namespace: str, body: V1PodDisruptionBudget, **kwargs: Any) -> Awaitable[V1PodDisruptionBudget]: ...
    def create_namespaced_pod_disruption_budget_with_http_info(self, namespace: str, body: V1PodDisruptionBudget, **kwargs: Any) -> Awaitable[tuple[V1PodDisruptionBudget, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_pod_disruption_budget(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_pod_disruption_budget_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_namespaced_pod_disruption_budget(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_namespaced_pod_disruption_budget_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_namespaced_pod_disruption_budget(self, namespace: str, **kwargs: Any) -> Awaitable[V1PodDisruptionBudgetList]: ...
    def list_namespaced_pod_disruption_budget_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1PodDisruptionBudgetList, int, CIMultiDictProxy]]: ...
    def list_pod_disruption_budget_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V1PodDisruptionBudgetList]: ...
    def list_pod_disruption_budget_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1PodDisruptionBudgetList, int, CIMultiDictProxy]]: ...
    def patch_namespaced_pod_disruption_budget(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1PodDisruptionBudget]: ...
    def patch_namespaced_pod_disruption_budget_status(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1PodDisruptionBudget]: ...
    def patch_namespaced_pod_disruption_budget_status_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1PodDisruptionBudget, int, CIMultiDictProxy]]: ...
    def patch_namespaced_pod_disruption_budget_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1PodDisruptionBudget, int, CIMultiDictProxy]]: ...
    def read_namespaced_pod_disruption_budget(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1PodDisruptionBudget]: ...
    def read_namespaced_pod_disruption_budget_status(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1PodDisruptionBudget]: ...
    def read_namespaced_pod_disruption_budget_status_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1PodDisruptionBudget, int, CIMultiDictProxy]]: ...
    def read_namespaced_pod_disruption_budget_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1PodDisruptionBudget, int, CIMultiDictProxy]]: ...
    def replace_namespaced_pod_disruption_budget(self, name: str, namespace: str, body: V1PodDisruptionBudget, **kwargs: Any) -> Awaitable[V1PodDisruptionBudget]: ...
    def replace_namespaced_pod_disruption_budget_status(self, name: str, namespace: str, body: V1PodDisruptionBudget, **kwargs: Any) -> Awaitable[V1PodDisruptionBudget]: ...
    def replace_namespaced_pod_disruption_budget_status_with_http_info(self, name: str, namespace: str, body: V1PodDisruptionBudget, **kwargs: Any) -> Awaitable[tuple[V1PodDisruptionBudget, int, CIMultiDictProxy]]: ...
    def replace_namespaced_pod_disruption_budget_with_http_info(self, name: str, namespace: str, body: V1PodDisruptionBudget, **kwargs: Any) -> Awaitable[tuple[V1PodDisruptionBudget, int, CIMultiDictProxy]]: ...
