from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import ResourceV1ResourceClaim
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1DeviceClass
from kubernetes_asyncio.client.models import V1DeviceClassList
from kubernetes_asyncio.client.models import V1ResourceClaimList
from kubernetes_asyncio.client.models import V1ResourceClaimTemplate
from kubernetes_asyncio.client.models import V1ResourceClaimTemplateList
from kubernetes_asyncio.client.models import V1ResourceSlice
from kubernetes_asyncio.client.models import V1ResourceSliceList
from kubernetes_asyncio.client.models import V1Status
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class ResourceV1Api:
    def __init__(self, api_client: ApiClient | None = None) -> None: ...
    def create_device_class(self, body: V1DeviceClass, **kwargs: Any) -> Awaitable[V1DeviceClass]: ...
    def create_device_class_with_http_info(self, body: V1DeviceClass, **kwargs: Any) -> Awaitable[tuple[V1DeviceClass, int, CIMultiDictProxy]]: ...
    def create_namespaced_resource_claim(self, namespace: str, body: ResourceV1ResourceClaim, **kwargs: Any) -> Awaitable[ResourceV1ResourceClaim]: ...
    def create_namespaced_resource_claim_template(self, namespace: str, body: V1ResourceClaimTemplate, **kwargs: Any) -> Awaitable[V1ResourceClaimTemplate]: ...
    def create_namespaced_resource_claim_template_with_http_info(self, namespace: str, body: V1ResourceClaimTemplate, **kwargs: Any) -> Awaitable[tuple[V1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def create_namespaced_resource_claim_with_http_info(self, namespace: str, body: ResourceV1ResourceClaim, **kwargs: Any) -> Awaitable[tuple[ResourceV1ResourceClaim, int, CIMultiDictProxy]]: ...
    def create_resource_slice(self, body: V1ResourceSlice, **kwargs: Any) -> Awaitable[V1ResourceSlice]: ...
    def create_resource_slice_with_http_info(self, body: V1ResourceSlice, **kwargs: Any) -> Awaitable[tuple[V1ResourceSlice, int, CIMultiDictProxy]]: ...
    def delete_collection_device_class(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_device_class_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_resource_claim(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_resource_claim_template(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_resource_claim_template_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_resource_claim_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_resource_slice(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_resource_slice_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_device_class(self, name: str, **kwargs: Any) -> Awaitable[V1DeviceClass]: ...
    def delete_device_class_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1DeviceClass, int, CIMultiDictProxy]]: ...
    def delete_namespaced_resource_claim(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[ResourceV1ResourceClaim]: ...
    def delete_namespaced_resource_claim_template(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1ResourceClaimTemplate]: ...
    def delete_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def delete_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[ResourceV1ResourceClaim, int, CIMultiDictProxy]]: ...
    def delete_resource_slice(self, name: str, **kwargs: Any) -> Awaitable[V1ResourceSlice]: ...
    def delete_resource_slice_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1ResourceSlice, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_device_class(self, **kwargs: Any) -> Awaitable[V1DeviceClassList]: ...
    def list_device_class_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1DeviceClassList, int, CIMultiDictProxy]]: ...
    def list_namespaced_resource_claim(self, namespace: str, **kwargs: Any) -> Awaitable[V1ResourceClaimList]: ...
    def list_namespaced_resource_claim_template(self, namespace: str, **kwargs: Any) -> Awaitable[V1ResourceClaimTemplateList]: ...
    def list_namespaced_resource_claim_template_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1ResourceClaimTemplateList, int, CIMultiDictProxy]]: ...
    def list_namespaced_resource_claim_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1ResourceClaimList, int, CIMultiDictProxy]]: ...
    def list_resource_claim_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V1ResourceClaimList]: ...
    def list_resource_claim_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1ResourceClaimList, int, CIMultiDictProxy]]: ...
    def list_resource_claim_template_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V1ResourceClaimTemplateList]: ...
    def list_resource_claim_template_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1ResourceClaimTemplateList, int, CIMultiDictProxy]]: ...
    def list_resource_slice(self, **kwargs: Any) -> Awaitable[V1ResourceSliceList]: ...
    def list_resource_slice_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1ResourceSliceList, int, CIMultiDictProxy]]: ...
    def patch_device_class(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1DeviceClass]: ...
    def patch_device_class_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1DeviceClass, int, CIMultiDictProxy]]: ...
    def patch_namespaced_resource_claim(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[ResourceV1ResourceClaim]: ...
    def patch_namespaced_resource_claim_status(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[ResourceV1ResourceClaim]: ...
    def patch_namespaced_resource_claim_status_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[ResourceV1ResourceClaim, int, CIMultiDictProxy]]: ...
    def patch_namespaced_resource_claim_template(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1ResourceClaimTemplate]: ...
    def patch_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def patch_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[ResourceV1ResourceClaim, int, CIMultiDictProxy]]: ...
    def patch_resource_slice(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1ResourceSlice]: ...
    def patch_resource_slice_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1ResourceSlice, int, CIMultiDictProxy]]: ...
    def read_device_class(self, name: str, **kwargs: Any) -> Awaitable[V1DeviceClass]: ...
    def read_device_class_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1DeviceClass, int, CIMultiDictProxy]]: ...
    def read_namespaced_resource_claim(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[ResourceV1ResourceClaim]: ...
    def read_namespaced_resource_claim_status(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[ResourceV1ResourceClaim]: ...
    def read_namespaced_resource_claim_status_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[ResourceV1ResourceClaim, int, CIMultiDictProxy]]: ...
    def read_namespaced_resource_claim_template(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1ResourceClaimTemplate]: ...
    def read_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def read_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[ResourceV1ResourceClaim, int, CIMultiDictProxy]]: ...
    def read_resource_slice(self, name: str, **kwargs: Any) -> Awaitable[V1ResourceSlice]: ...
    def read_resource_slice_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1ResourceSlice, int, CIMultiDictProxy]]: ...
    def replace_device_class(self, name: str, body: V1DeviceClass, **kwargs: Any) -> Awaitable[V1DeviceClass]: ...
    def replace_device_class_with_http_info(self, name: str, body: V1DeviceClass, **kwargs: Any) -> Awaitable[tuple[V1DeviceClass, int, CIMultiDictProxy]]: ...
    def replace_namespaced_resource_claim(self, name: str, namespace: str, body: ResourceV1ResourceClaim, **kwargs: Any) -> Awaitable[ResourceV1ResourceClaim]: ...
    def replace_namespaced_resource_claim_status(self, name: str, namespace: str, body: ResourceV1ResourceClaim, **kwargs: Any) -> Awaitable[ResourceV1ResourceClaim]: ...
    def replace_namespaced_resource_claim_status_with_http_info(self, name: str, namespace: str, body: ResourceV1ResourceClaim, **kwargs: Any) -> Awaitable[tuple[ResourceV1ResourceClaim, int, CIMultiDictProxy]]: ...
    def replace_namespaced_resource_claim_template(self, name: str, namespace: str, body: V1ResourceClaimTemplate, **kwargs: Any) -> Awaitable[V1ResourceClaimTemplate]: ...
    def replace_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, body: V1ResourceClaimTemplate, **kwargs: Any) -> Awaitable[tuple[V1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def replace_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, body: ResourceV1ResourceClaim, **kwargs: Any) -> Awaitable[tuple[ResourceV1ResourceClaim, int, CIMultiDictProxy]]: ...
    def replace_resource_slice(self, name: str, body: V1ResourceSlice, **kwargs: Any) -> Awaitable[V1ResourceSlice]: ...
    def replace_resource_slice_with_http_info(self, name: str, body: V1ResourceSlice, **kwargs: Any) -> Awaitable[tuple[V1ResourceSlice, int, CIMultiDictProxy]]: ...
