from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1beta1DeviceClass
from kubernetes_asyncio.client.models import V1beta1DeviceClassList
from kubernetes_asyncio.client.models import V1beta1ResourceClaim
from kubernetes_asyncio.client.models import V1beta1ResourceClaimList
from kubernetes_asyncio.client.models import V1beta1ResourceClaimTemplate
from kubernetes_asyncio.client.models import V1beta1ResourceClaimTemplateList
from kubernetes_asyncio.client.models import V1beta1ResourceSlice
from kubernetes_asyncio.client.models import V1beta1ResourceSliceList
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class ResourceV1beta1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_device_class(self, body: V1beta1DeviceClass, **kwargs: Any) -> Awaitable[V1beta1DeviceClass]: ...
    def create_device_class_with_http_info(self, body: V1beta1DeviceClass, **kwargs: Any) -> Awaitable[tuple[V1beta1DeviceClass, int, CIMultiDictProxy]]: ...
    def create_namespaced_resource_claim(self, namespace: str, body: V1beta1ResourceClaim, **kwargs: Any) -> Awaitable[V1beta1ResourceClaim]: ...
    def create_namespaced_resource_claim_template(self, namespace: str, body: V1beta1ResourceClaimTemplate, **kwargs: Any) -> Awaitable[V1beta1ResourceClaimTemplate]: ...
    def create_namespaced_resource_claim_template_with_http_info(self, namespace: str, body: V1beta1ResourceClaimTemplate, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def create_namespaced_resource_claim_with_http_info(self, namespace: str, body: V1beta1ResourceClaim, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaim, int, CIMultiDictProxy]]: ...
    def create_resource_slice(self, body: V1beta1ResourceSlice, **kwargs: Any) -> Awaitable[V1beta1ResourceSlice]: ...
    def create_resource_slice_with_http_info(self, body: V1beta1ResourceSlice, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceSlice, int, CIMultiDictProxy]]: ...
    def delete_collection_device_class(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_device_class_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_resource_claim(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_resource_claim_template(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_resource_claim_template_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_resource_claim_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_resource_slice(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_resource_slice_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_device_class(self, name: str, **kwargs: Any) -> Awaitable[V1beta1DeviceClass]: ...
    def delete_device_class_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1beta1DeviceClass, int, CIMultiDictProxy]]: ...
    def delete_namespaced_resource_claim(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1beta1ResourceClaim]: ...
    def delete_namespaced_resource_claim_template(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1beta1ResourceClaimTemplate]: ...
    def delete_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def delete_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaim, int, CIMultiDictProxy]]: ...
    def delete_resource_slice(self, name: str, **kwargs: Any) -> Awaitable[V1beta1ResourceSlice]: ...
    def delete_resource_slice_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceSlice, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_device_class(self, **kwargs: Any) -> Awaitable[V1beta1DeviceClassList]: ...
    def list_device_class_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1beta1DeviceClassList, int, CIMultiDictProxy]]: ...
    def list_namespaced_resource_claim(self, namespace: str, **kwargs: Any) -> Awaitable[V1beta1ResourceClaimList]: ...
    def list_namespaced_resource_claim_template(self, namespace: str, **kwargs: Any) -> Awaitable[V1beta1ResourceClaimTemplateList]: ...
    def list_namespaced_resource_claim_template_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaimTemplateList, int, CIMultiDictProxy]]: ...
    def list_namespaced_resource_claim_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaimList, int, CIMultiDictProxy]]: ...
    def list_resource_claim_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V1beta1ResourceClaimList]: ...
    def list_resource_claim_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaimList, int, CIMultiDictProxy]]: ...
    def list_resource_claim_template_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V1beta1ResourceClaimTemplateList]: ...
    def list_resource_claim_template_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaimTemplateList, int, CIMultiDictProxy]]: ...
    def list_resource_slice(self, **kwargs: Any) -> Awaitable[V1beta1ResourceSliceList]: ...
    def list_resource_slice_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceSliceList, int, CIMultiDictProxy]]: ...
    def patch_device_class(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1beta1DeviceClass]: ...
    def patch_device_class_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1beta1DeviceClass, int, CIMultiDictProxy]]: ...
    def patch_namespaced_resource_claim(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1beta1ResourceClaim]: ...
    def patch_namespaced_resource_claim_status(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1beta1ResourceClaim]: ...
    def patch_namespaced_resource_claim_status_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaim, int, CIMultiDictProxy]]: ...
    def patch_namespaced_resource_claim_template(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1beta1ResourceClaimTemplate]: ...
    def patch_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def patch_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaim, int, CIMultiDictProxy]]: ...
    def patch_resource_slice(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1beta1ResourceSlice]: ...
    def patch_resource_slice_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceSlice, int, CIMultiDictProxy]]: ...
    def read_device_class(self, name: str, **kwargs: Any) -> Awaitable[V1beta1DeviceClass]: ...
    def read_device_class_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1beta1DeviceClass, int, CIMultiDictProxy]]: ...
    def read_namespaced_resource_claim(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1beta1ResourceClaim]: ...
    def read_namespaced_resource_claim_status(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1beta1ResourceClaim]: ...
    def read_namespaced_resource_claim_status_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaim, int, CIMultiDictProxy]]: ...
    def read_namespaced_resource_claim_template(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1beta1ResourceClaimTemplate]: ...
    def read_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def read_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaim, int, CIMultiDictProxy]]: ...
    def read_resource_slice(self, name: str, **kwargs: Any) -> Awaitable[V1beta1ResourceSlice]: ...
    def read_resource_slice_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceSlice, int, CIMultiDictProxy]]: ...
    def replace_device_class(self, name: str, body: V1beta1DeviceClass, **kwargs: Any) -> Awaitable[V1beta1DeviceClass]: ...
    def replace_device_class_with_http_info(self, name: str, body: V1beta1DeviceClass, **kwargs: Any) -> Awaitable[tuple[V1beta1DeviceClass, int, CIMultiDictProxy]]: ...
    def replace_namespaced_resource_claim(self, name: str, namespace: str, body: V1beta1ResourceClaim, **kwargs: Any) -> Awaitable[V1beta1ResourceClaim]: ...
    def replace_namespaced_resource_claim_status(self, name: str, namespace: str, body: V1beta1ResourceClaim, **kwargs: Any) -> Awaitable[V1beta1ResourceClaim]: ...
    def replace_namespaced_resource_claim_status_with_http_info(self, name: str, namespace: str, body: V1beta1ResourceClaim, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaim, int, CIMultiDictProxy]]: ...
    def replace_namespaced_resource_claim_template(self, name: str, namespace: str, body: V1beta1ResourceClaimTemplate, **kwargs: Any) -> Awaitable[V1beta1ResourceClaimTemplate]: ...
    def replace_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, body: V1beta1ResourceClaimTemplate, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def replace_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, body: V1beta1ResourceClaim, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceClaim, int, CIMultiDictProxy]]: ...
    def replace_resource_slice(self, name: str, body: V1beta1ResourceSlice, **kwargs: Any) -> Awaitable[V1beta1ResourceSlice]: ...
    def replace_resource_slice_with_http_info(self, name: str, body: V1beta1ResourceSlice, **kwargs: Any) -> Awaitable[tuple[V1beta1ResourceSlice, int, CIMultiDictProxy]]: ...
