from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1alpha3DeviceClass
from kubernetes_asyncio.client.models import V1alpha3DeviceClassList
from kubernetes_asyncio.client.models import V1alpha3DeviceTaintRule
from kubernetes_asyncio.client.models import V1alpha3DeviceTaintRuleList
from kubernetes_asyncio.client.models import V1alpha3ResourceClaim
from kubernetes_asyncio.client.models import V1alpha3ResourceClaimList
from kubernetes_asyncio.client.models import V1alpha3ResourceClaimTemplate
from kubernetes_asyncio.client.models import V1alpha3ResourceClaimTemplateList
from kubernetes_asyncio.client.models import V1alpha3ResourceSlice
from kubernetes_asyncio.client.models import V1alpha3ResourceSliceList
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class ResourceV1alpha3Api:
    def __init__(self, api_client: ApiClient | None = None) -> None: ...
    def create_device_class(self, body: V1alpha3DeviceClass, **kwargs: Any) -> Awaitable[V1alpha3DeviceClass]: ...
    def create_device_class_with_http_info(self, body: V1alpha3DeviceClass, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceClass, int, CIMultiDictProxy]]: ...
    def create_device_taint_rule(self, body: V1alpha3DeviceTaintRule, **kwargs: Any) -> Awaitable[V1alpha3DeviceTaintRule]: ...
    def create_device_taint_rule_with_http_info(self, body: V1alpha3DeviceTaintRule, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceTaintRule, int, CIMultiDictProxy]]: ...
    def create_namespaced_resource_claim(self, namespace: str, body: V1alpha3ResourceClaim, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaim]: ...
    def create_namespaced_resource_claim_template(self, namespace: str, body: V1alpha3ResourceClaimTemplate, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaimTemplate]: ...
    def create_namespaced_resource_claim_template_with_http_info(self, namespace: str, body: V1alpha3ResourceClaimTemplate, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def create_namespaced_resource_claim_with_http_info(self, namespace: str, body: V1alpha3ResourceClaim, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaim, int, CIMultiDictProxy]]: ...
    def create_resource_slice(self, body: V1alpha3ResourceSlice, **kwargs: Any) -> Awaitable[V1alpha3ResourceSlice]: ...
    def create_resource_slice_with_http_info(self, body: V1alpha3ResourceSlice, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceSlice, int, CIMultiDictProxy]]: ...
    def delete_collection_device_class(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_device_class_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_device_taint_rule(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_device_taint_rule_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_resource_claim(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_resource_claim_template(self, namespace: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_namespaced_resource_claim_template_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_namespaced_resource_claim_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_collection_resource_slice(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_resource_slice_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_device_class(self, name: str, **kwargs: Any) -> Awaitable[V1alpha3DeviceClass]: ...
    def delete_device_class_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceClass, int, CIMultiDictProxy]]: ...
    def delete_device_taint_rule(self, name: str, **kwargs: Any) -> Awaitable[V1alpha3DeviceTaintRule]: ...
    def delete_device_taint_rule_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceTaintRule, int, CIMultiDictProxy]]: ...
    def delete_namespaced_resource_claim(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaim]: ...
    def delete_namespaced_resource_claim_template(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaimTemplate]: ...
    def delete_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def delete_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaim, int, CIMultiDictProxy]]: ...
    def delete_resource_slice(self, name: str, **kwargs: Any) -> Awaitable[V1alpha3ResourceSlice]: ...
    def delete_resource_slice_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceSlice, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_device_class(self, **kwargs: Any) -> Awaitable[V1alpha3DeviceClassList]: ...
    def list_device_class_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceClassList, int, CIMultiDictProxy]]: ...
    def list_device_taint_rule(self, **kwargs: Any) -> Awaitable[V1alpha3DeviceTaintRuleList]: ...
    def list_device_taint_rule_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceTaintRuleList, int, CIMultiDictProxy]]: ...
    def list_namespaced_resource_claim(self, namespace: str, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaimList]: ...
    def list_namespaced_resource_claim_template(self, namespace: str, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaimTemplateList]: ...
    def list_namespaced_resource_claim_template_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaimTemplateList, int, CIMultiDictProxy]]: ...
    def list_namespaced_resource_claim_with_http_info(self, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaimList, int, CIMultiDictProxy]]: ...
    def list_resource_claim_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaimList]: ...
    def list_resource_claim_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaimList, int, CIMultiDictProxy]]: ...
    def list_resource_claim_template_for_all_namespaces(self, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaimTemplateList]: ...
    def list_resource_claim_template_for_all_namespaces_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaimTemplateList, int, CIMultiDictProxy]]: ...
    def list_resource_slice(self, **kwargs: Any) -> Awaitable[V1alpha3ResourceSliceList]: ...
    def list_resource_slice_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceSliceList, int, CIMultiDictProxy]]: ...
    def patch_device_class(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha3DeviceClass]: ...
    def patch_device_class_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceClass, int, CIMultiDictProxy]]: ...
    def patch_device_taint_rule(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha3DeviceTaintRule]: ...
    def patch_device_taint_rule_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceTaintRule, int, CIMultiDictProxy]]: ...
    def patch_namespaced_resource_claim(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaim]: ...
    def patch_namespaced_resource_claim_status(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaim]: ...
    def patch_namespaced_resource_claim_status_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaim, int, CIMultiDictProxy]]: ...
    def patch_namespaced_resource_claim_template(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaimTemplate]: ...
    def patch_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def patch_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaim, int, CIMultiDictProxy]]: ...
    def patch_resource_slice(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1alpha3ResourceSlice]: ...
    def patch_resource_slice_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceSlice, int, CIMultiDictProxy]]: ...
    def read_device_class(self, name: str, **kwargs: Any) -> Awaitable[V1alpha3DeviceClass]: ...
    def read_device_class_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceClass, int, CIMultiDictProxy]]: ...
    def read_device_taint_rule(self, name: str, **kwargs: Any) -> Awaitable[V1alpha3DeviceTaintRule]: ...
    def read_device_taint_rule_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceTaintRule, int, CIMultiDictProxy]]: ...
    def read_namespaced_resource_claim(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaim]: ...
    def read_namespaced_resource_claim_status(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaim]: ...
    def read_namespaced_resource_claim_status_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaim, int, CIMultiDictProxy]]: ...
    def read_namespaced_resource_claim_template(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaimTemplate]: ...
    def read_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def read_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaim, int, CIMultiDictProxy]]: ...
    def read_resource_slice(self, name: str, **kwargs: Any) -> Awaitable[V1alpha3ResourceSlice]: ...
    def read_resource_slice_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceSlice, int, CIMultiDictProxy]]: ...
    def replace_device_class(self, name: str, body: V1alpha3DeviceClass, **kwargs: Any) -> Awaitable[V1alpha3DeviceClass]: ...
    def replace_device_class_with_http_info(self, name: str, body: V1alpha3DeviceClass, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceClass, int, CIMultiDictProxy]]: ...
    def replace_device_taint_rule(self, name: str, body: V1alpha3DeviceTaintRule, **kwargs: Any) -> Awaitable[V1alpha3DeviceTaintRule]: ...
    def replace_device_taint_rule_with_http_info(self, name: str, body: V1alpha3DeviceTaintRule, **kwargs: Any) -> Awaitable[tuple[V1alpha3DeviceTaintRule, int, CIMultiDictProxy]]: ...
    def replace_namespaced_resource_claim(self, name: str, namespace: str, body: V1alpha3ResourceClaim, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaim]: ...
    def replace_namespaced_resource_claim_status(self, name: str, namespace: str, body: V1alpha3ResourceClaim, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaim]: ...
    def replace_namespaced_resource_claim_status_with_http_info(self, name: str, namespace: str, body: V1alpha3ResourceClaim, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaim, int, CIMultiDictProxy]]: ...
    def replace_namespaced_resource_claim_template(self, name: str, namespace: str, body: V1alpha3ResourceClaimTemplate, **kwargs: Any) -> Awaitable[V1alpha3ResourceClaimTemplate]: ...
    def replace_namespaced_resource_claim_template_with_http_info(self, name: str, namespace: str, body: V1alpha3ResourceClaimTemplate, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaimTemplate, int, CIMultiDictProxy]]: ...
    def replace_namespaced_resource_claim_with_http_info(self, name: str, namespace: str, body: V1alpha3ResourceClaim, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceClaim, int, CIMultiDictProxy]]: ...
    def replace_resource_slice(self, name: str, body: V1alpha3ResourceSlice, **kwargs: Any) -> Awaitable[V1alpha3ResourceSlice]: ...
    def replace_resource_slice_with_http_info(self, name: str, body: V1alpha3ResourceSlice, **kwargs: Any) -> Awaitable[tuple[V1alpha3ResourceSlice, int, CIMultiDictProxy]]: ...
