from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1PriorityClass
from kubernetes_asyncio.client.models import V1PriorityClassList
from kubernetes_asyncio.client.models import V1Status
from multidict import CIMultiDictProxy
from typing import Any

class SchedulingV1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_priority_class(self, body: V1PriorityClass, kwargs: Any) -> V1PriorityClass: ...
    def create_priority_class_with_http_info(self, body: V1PriorityClass, kwargs: Any) -> tuple[V1PriorityClass, int, CIMultiDictProxy]: ...
    def delete_collection_priority_class(self, kwargs: Any) -> V1Status: ...
    def delete_collection_priority_class_with_http_info(self, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_priority_class(self, name: str, kwargs: Any) -> V1Status: ...
    def delete_priority_class_with_http_info(self, name: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def get_api_resources(self, kwargs: Any) -> V1APIResourceList: ...
    def get_api_resources_with_http_info(self, kwargs: Any) -> tuple[V1APIResourceList, int, CIMultiDictProxy]: ...
    def list_priority_class(self, kwargs: Any) -> V1PriorityClassList: ...
    def list_priority_class_with_http_info(self, kwargs: Any) -> tuple[V1PriorityClassList, int, CIMultiDictProxy]: ...
    def patch_priority_class(self, name: str, body: Any, kwargs: Any) -> V1PriorityClass: ...
    def patch_priority_class_with_http_info(self, name: str, body: Any, kwargs: Any) -> tuple[V1PriorityClass, int, CIMultiDictProxy]: ...
    def read_priority_class(self, name: str, kwargs: Any) -> V1PriorityClass: ...
    def read_priority_class_with_http_info(self, name: str, kwargs: Any) -> tuple[V1PriorityClass, int, CIMultiDictProxy]: ...
    def replace_priority_class(self, name: str, body: V1PriorityClass, kwargs: Any) -> V1PriorityClass: ...
    def replace_priority_class_with_http_info(self, name: str, body: V1PriorityClass, kwargs: Any) -> tuple[V1PriorityClass, int, CIMultiDictProxy]: ...
