from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1PriorityClass
from kubernetes_asyncio.client.models import V1PriorityClassList
from kubernetes_asyncio.client.models import V1Status
from multidict import CIMultiDictProxy
from typing import Any
from typing import Awaitable

class SchedulingV1Api:
    def __init__(self, api_client: ApiClient | None = None) -> None: ...
    def create_priority_class(self, body: V1PriorityClass, **kwargs: Any) -> Awaitable[V1PriorityClass]: ...
    def create_priority_class_with_http_info(self, body: V1PriorityClass, **kwargs: Any) -> Awaitable[tuple[V1PriorityClass, int, CIMultiDictProxy]]: ...
    def delete_collection_priority_class(self, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_collection_priority_class_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def delete_priority_class(self, name: str, **kwargs: Any) -> Awaitable[V1Status]: ...
    def delete_priority_class_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1Status, int, CIMultiDictProxy]]: ...
    def get_api_resources(self, **kwargs: Any) -> Awaitable[V1APIResourceList]: ...
    def get_api_resources_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1APIResourceList, int, CIMultiDictProxy]]: ...
    def list_priority_class(self, **kwargs: Any) -> Awaitable[V1PriorityClassList]: ...
    def list_priority_class_with_http_info(self, **kwargs: Any) -> Awaitable[tuple[V1PriorityClassList, int, CIMultiDictProxy]]: ...
    def patch_priority_class(self, name: str, body: Any, **kwargs: Any) -> Awaitable[V1PriorityClass]: ...
    def patch_priority_class_with_http_info(self, name: str, body: Any, **kwargs: Any) -> Awaitable[tuple[V1PriorityClass, int, CIMultiDictProxy]]: ...
    def read_priority_class(self, name: str, **kwargs: Any) -> Awaitable[V1PriorityClass]: ...
    def read_priority_class_with_http_info(self, name: str, **kwargs: Any) -> Awaitable[tuple[V1PriorityClass, int, CIMultiDictProxy]]: ...
    def replace_priority_class(self, name: str, body: V1PriorityClass, **kwargs: Any) -> Awaitable[V1PriorityClass]: ...
    def replace_priority_class_with_http_info(self, name: str, body: V1PriorityClass, **kwargs: Any) -> Awaitable[tuple[V1PriorityClass, int, CIMultiDictProxy]]: ...
