from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1alpha1VolumeAttributesClass
from kubernetes_asyncio.client.models import V1alpha1VolumeAttributesClassList
from multidict import CIMultiDictProxy
from typing import Any

class StorageV1alpha1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_volume_attributes_class(self, body: V1alpha1VolumeAttributesClass, kwargs: Any) -> V1alpha1VolumeAttributesClass: ...
    def create_volume_attributes_class_with_http_info(self, body: V1alpha1VolumeAttributesClass, kwargs: Any) -> tuple[V1alpha1VolumeAttributesClass, int, CIMultiDictProxy]: ...
    def delete_collection_volume_attributes_class(self, kwargs: Any) -> V1Status: ...
    def delete_collection_volume_attributes_class_with_http_info(self, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_volume_attributes_class(self, name: str, kwargs: Any) -> V1alpha1VolumeAttributesClass: ...
    def delete_volume_attributes_class_with_http_info(self, name: str, kwargs: Any) -> tuple[V1alpha1VolumeAttributesClass, int, CIMultiDictProxy]: ...
    def get_api_resources(self, kwargs: Any) -> V1APIResourceList: ...
    def get_api_resources_with_http_info(self, kwargs: Any) -> tuple[V1APIResourceList, int, CIMultiDictProxy]: ...
    def list_volume_attributes_class(self, kwargs: Any) -> V1alpha1VolumeAttributesClassList: ...
    def list_volume_attributes_class_with_http_info(self, kwargs: Any) -> tuple[V1alpha1VolumeAttributesClassList, int, CIMultiDictProxy]: ...
    def patch_volume_attributes_class(self, name: str, body: Any, kwargs: Any) -> V1alpha1VolumeAttributesClass: ...
    def patch_volume_attributes_class_with_http_info(self, name: str, body: Any, kwargs: Any) -> tuple[V1alpha1VolumeAttributesClass, int, CIMultiDictProxy]: ...
    def read_volume_attributes_class(self, name: str, kwargs: Any) -> V1alpha1VolumeAttributesClass: ...
    def read_volume_attributes_class_with_http_info(self, name: str, kwargs: Any) -> tuple[V1alpha1VolumeAttributesClass, int, CIMultiDictProxy]: ...
    def replace_volume_attributes_class(self, name: str, body: V1alpha1VolumeAttributesClass, kwargs: Any) -> V1alpha1VolumeAttributesClass: ...
    def replace_volume_attributes_class_with_http_info(self, name: str, body: V1alpha1VolumeAttributesClass, kwargs: Any) -> tuple[V1alpha1VolumeAttributesClass, int, CIMultiDictProxy]: ...
