from kubernetes_asyncio.client.api_client import ApiClient
from kubernetes_asyncio.client.models import V1APIResourceList
from kubernetes_asyncio.client.models import V1Status
from kubernetes_asyncio.client.models import V1alpha1StorageVersionMigration
from kubernetes_asyncio.client.models import V1alpha1StorageVersionMigrationList
from multidict import CIMultiDictProxy
from typing import Any

class StoragemigrationV1alpha1Api:
    def __init__(self, api_client: ApiClient) -> None: ...
    def create_storage_version_migration(self, body: V1alpha1StorageVersionMigration, kwargs: Any) -> V1alpha1StorageVersionMigration: ...
    def create_storage_version_migration_with_http_info(self, body: V1alpha1StorageVersionMigration, kwargs: Any) -> tuple[V1alpha1StorageVersionMigration, int, CIMultiDictProxy]: ...
    def delete_collection_storage_version_migration(self, kwargs: Any) -> V1Status: ...
    def delete_collection_storage_version_migration_with_http_info(self, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def delete_storage_version_migration(self, name: str, kwargs: Any) -> V1Status: ...
    def delete_storage_version_migration_with_http_info(self, name: str, kwargs: Any) -> tuple[V1Status, int, CIMultiDictProxy]: ...
    def get_api_resources(self, kwargs: Any) -> V1APIResourceList: ...
    def get_api_resources_with_http_info(self, kwargs: Any) -> tuple[V1APIResourceList, int, CIMultiDictProxy]: ...
    def list_storage_version_migration(self, kwargs: Any) -> V1alpha1StorageVersionMigrationList: ...
    def list_storage_version_migration_with_http_info(self, kwargs: Any) -> tuple[V1alpha1StorageVersionMigrationList, int, CIMultiDictProxy]: ...
    def patch_storage_version_migration(self, name: str, body: Any, kwargs: Any) -> V1alpha1StorageVersionMigration: ...
    def patch_storage_version_migration_status(self, name: str, body: Any, kwargs: Any) -> V1alpha1StorageVersionMigration: ...
    def patch_storage_version_migration_status_with_http_info(self, name: str, body: Any, kwargs: Any) -> tuple[V1alpha1StorageVersionMigration, int, CIMultiDictProxy]: ...
    def patch_storage_version_migration_with_http_info(self, name: str, body: Any, kwargs: Any) -> tuple[V1alpha1StorageVersionMigration, int, CIMultiDictProxy]: ...
    def read_storage_version_migration(self, name: str, kwargs: Any) -> V1alpha1StorageVersionMigration: ...
    def read_storage_version_migration_status(self, name: str, kwargs: Any) -> V1alpha1StorageVersionMigration: ...
    def read_storage_version_migration_status_with_http_info(self, name: str, kwargs: Any) -> tuple[V1alpha1StorageVersionMigration, int, CIMultiDictProxy]: ...
    def read_storage_version_migration_with_http_info(self, name: str, kwargs: Any) -> tuple[V1alpha1StorageVersionMigration, int, CIMultiDictProxy]: ...
    def replace_storage_version_migration(self, name: str, body: V1alpha1StorageVersionMigration, kwargs: Any) -> V1alpha1StorageVersionMigration: ...
    def replace_storage_version_migration_status(self, name: str, body: V1alpha1StorageVersionMigration, kwargs: Any) -> V1alpha1StorageVersionMigration: ...
    def replace_storage_version_migration_status_with_http_info(self, name: str, body: V1alpha1StorageVersionMigration, kwargs: Any) -> tuple[V1alpha1StorageVersionMigration, int, CIMultiDictProxy]: ...
    def replace_storage_version_migration_with_http_info(self, name: str, body: V1alpha1StorageVersionMigration, kwargs: Any) -> tuple[V1alpha1StorageVersionMigration, int, CIMultiDictProxy]: ...
