# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.13.5
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.admissionregistration_v1beta1_webhook_client_config import AdmissionregistrationV1beta1WebhookClientConfig  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestAdmissionregistrationV1beta1WebhookClientConfig(unittest.TestCase):
    """AdmissionregistrationV1beta1WebhookClientConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdmissionregistrationV1beta1WebhookClientConfig(self):
        """Test AdmissionregistrationV1beta1WebhookClientConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.admissionregistration_v1beta1_webhook_client_config.AdmissionregistrationV1beta1WebhookClientConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
