# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.11
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_token_request_spec import V1TokenRequestSpec  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1TokenRequestSpec(unittest.TestCase):
    """V1TokenRequestSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1TokenRequestSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1_token_request_spec.V1TokenRequestSpec()  # noqa: E501
        if include_optional :
            return V1TokenRequestSpec(
                audiences = [
                    ''
                    ], 
                bound_object_ref = kubernetes_asyncio.client.models.v1/bound_object_reference.v1.BoundObjectReference(
                    api_version = '', 
                    kind = '', 
                    name = '', 
                    uid = '', ), 
                expiration_seconds = 56
            )
        else :
            return V1TokenRequestSpec(
                audiences = [
                    ''
                    ],
        )

    def testV1TokenRequestSpec(self):
        """Test V1TokenRequestSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
