# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.14.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.apps_v1beta1_deployment_spec import AppsV1beta1DeploymentSpec  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestAppsV1beta1DeploymentSpec(unittest.TestCase):
    """AppsV1beta1DeploymentSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppsV1beta1DeploymentSpec(self):
        """Test AppsV1beta1DeploymentSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.apps_v1beta1_deployment_spec.AppsV1beta1DeploymentSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
