# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.12.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_load_balancer_status import V1LoadBalancerStatus  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1LoadBalancerStatus(unittest.TestCase):
    """V1LoadBalancerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1LoadBalancerStatus(self):
        """Test V1LoadBalancerStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1_load_balancer_status.V1LoadBalancerStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
