# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.33.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta1_cel_device_selector import V1beta1CELDeviceSelector  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1beta1CELDeviceSelector(unittest.TestCase):
    """V1beta1CELDeviceSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1beta1CELDeviceSelector
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1beta1_cel_device_selector.V1beta1CELDeviceSelector()  # noqa: E501
        if include_optional :
            return V1beta1CELDeviceSelector(
                expression = ''
            )
        else :
            return V1beta1CELDeviceSelector(
                expression = '',
        )

    def testV1beta1CELDeviceSelector(self):
        """Test V1beta1CELDeviceSelector"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
