# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.12.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_replication_controller_status import V1ReplicationControllerStatus  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1ReplicationControllerStatus(unittest.TestCase):
    """V1ReplicationControllerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ReplicationControllerStatus(self):
        """Test V1ReplicationControllerStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1_replication_controller_status.V1ReplicationControllerStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
