# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.33.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_scale_io_persistent_volume_source import V1ScaleIOPersistentVolumeSource  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1ScaleIOPersistentVolumeSource(unittest.TestCase):
    """V1ScaleIOPersistentVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1ScaleIOPersistentVolumeSource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1_scale_io_persistent_volume_source.V1ScaleIOPersistentVolumeSource()  # noqa: E501
        if include_optional :
            return V1ScaleIOPersistentVolumeSource(
                fs_type = '', 
                gateway = '', 
                protection_domain = '', 
                read_only = True, 
                secret_ref = kubernetes_asyncio.client.models.v1/secret_reference.v1.SecretReference(
                    name = '', 
                    namespace = '', ), 
                ssl_enabled = True, 
                storage_mode = '', 
                storage_pool = '', 
                system = '', 
                volume_name = ''
            )
        else :
            return V1ScaleIOPersistentVolumeSource(
                gateway = '',
                secret_ref = kubernetes_asyncio.client.models.v1/secret_reference.v1.SecretReference(
                    name = '', 
                    namespace = '', ),
                system = '',
        )

    def testV1ScaleIOPersistentVolumeSource(self):
        """Test V1ScaleIOPersistentVolumeSource"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
