# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.12.6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.extensions_v1beta1_allowed_host_path import ExtensionsV1beta1AllowedHostPath  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestExtensionsV1beta1AllowedHostPath(unittest.TestCase):
    """ExtensionsV1beta1AllowedHostPath unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtensionsV1beta1AllowedHostPath(self):
        """Test ExtensionsV1beta1AllowedHostPath"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.extensions_v1beta1_allowed_host_path.ExtensionsV1beta1AllowedHostPath()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
