# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.11.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta2_stateful_set_update_strategy import V1beta2StatefulSetUpdateStrategy  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1beta2StatefulSetUpdateStrategy(unittest.TestCase):
    """V1beta2StatefulSetUpdateStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta2StatefulSetUpdateStrategy(self):
        """Test V1beta2StatefulSetUpdateStrategy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1beta2_stateful_set_update_strategy.V1beta2StatefulSetUpdateStrategy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
