# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.11
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta1_priority_level_configuration_list import V1beta1PriorityLevelConfigurationList  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1beta1PriorityLevelConfigurationList(unittest.TestCase):
    """V1beta1PriorityLevelConfigurationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1beta1PriorityLevelConfigurationList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1beta1_priority_level_configuration_list.V1beta1PriorityLevelConfigurationList()  # noqa: E501
        if include_optional :
            return V1beta1PriorityLevelConfigurationList(
                api_version = '', 
                items = [
                    kubernetes_asyncio.client.models.v1beta1/priority_level_configuration.v1beta1.PriorityLevelConfiguration(
                        api_version = '', 
                        kind = '', 
                        metadata = kubernetes_asyncio.client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            generation = 56, 
                            labels = {
                                'key' : ''
                                }, 
                            managed_fields = [
                                kubernetes_asyncio.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '', 
                                    fields_type = '', 
                                    fields_v1 = kubernetes_asyncio.client.models.fields_v1.fieldsV1(), 
                                    manager = '', 
                                    operation = '', 
                                    subresource = '', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '', 
                            namespace = '', 
                            owner_references = [
                                kubernetes_asyncio.client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '', 
                                    name = '', 
                                    uid = '', )
                                ], 
                            resource_version = '', 
                            self_link = '', 
                            uid = '', ), 
                        spec = kubernetes_asyncio.client.models.v1beta1/priority_level_configuration_spec.v1beta1.PriorityLevelConfigurationSpec(
                            limited = kubernetes_asyncio.client.models.v1beta1/limited_priority_level_configuration.v1beta1.LimitedPriorityLevelConfiguration(
                                assured_concurrency_shares = 56, 
                                limit_response = kubernetes_asyncio.client.models.v1beta1/limit_response.v1beta1.LimitResponse(
                                    queuing = kubernetes_asyncio.client.models.v1beta1/queuing_configuration.v1beta1.QueuingConfiguration(
                                        hand_size = 56, 
                                        queue_length_limit = 56, 
                                        queues = 56, ), 
                                    type = '', ), ), 
                            type = '', ), 
                        status = kubernetes_asyncio.client.models.v1beta1/priority_level_configuration_status.v1beta1.PriorityLevelConfigurationStatus(
                            conditions = [
                                kubernetes_asyncio.client.models.v1beta1/priority_level_configuration_condition.v1beta1.PriorityLevelConfigurationCondition(
                                    last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    message = '', 
                                    reason = '', 
                                    type = '', )
                                ], ), )
                    ], 
                kind = '', 
                metadata = kubernetes_asyncio.client.models.v1/list_meta.v1.ListMeta(
                    continue = '', 
                    remaining_item_count = 56, 
                    resource_version = '', 
                    self_link = '', )
            )
        else :
            return V1beta1PriorityLevelConfigurationList(
                items = [
                    kubernetes_asyncio.client.models.v1beta1/priority_level_configuration.v1beta1.PriorityLevelConfiguration(
                        api_version = '', 
                        kind = '', 
                        metadata = kubernetes_asyncio.client.models.v1/object_meta.v1.ObjectMeta(
                            annotations = {
                                'key' : ''
                                }, 
                            creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deletion_grace_period_seconds = 56, 
                            deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            finalizers = [
                                ''
                                ], 
                            generate_name = '', 
                            generation = 56, 
                            labels = {
                                'key' : ''
                                }, 
                            managed_fields = [
                                kubernetes_asyncio.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                                    api_version = '', 
                                    fields_type = '', 
                                    fields_v1 = kubernetes_asyncio.client.models.fields_v1.fieldsV1(), 
                                    manager = '', 
                                    operation = '', 
                                    subresource = '', 
                                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            name = '', 
                            namespace = '', 
                            owner_references = [
                                kubernetes_asyncio.client.models.v1/owner_reference.v1.OwnerReference(
                                    api_version = '', 
                                    block_owner_deletion = True, 
                                    controller = True, 
                                    kind = '', 
                                    name = '', 
                                    uid = '', )
                                ], 
                            resource_version = '', 
                            self_link = '', 
                            uid = '', ), 
                        spec = kubernetes_asyncio.client.models.v1beta1/priority_level_configuration_spec.v1beta1.PriorityLevelConfigurationSpec(
                            limited = kubernetes_asyncio.client.models.v1beta1/limited_priority_level_configuration.v1beta1.LimitedPriorityLevelConfiguration(
                                assured_concurrency_shares = 56, 
                                limit_response = kubernetes_asyncio.client.models.v1beta1/limit_response.v1beta1.LimitResponse(
                                    queuing = kubernetes_asyncio.client.models.v1beta1/queuing_configuration.v1beta1.QueuingConfiguration(
                                        hand_size = 56, 
                                        queue_length_limit = 56, 
                                        queues = 56, ), 
                                    type = '', ), ), 
                            type = '', ), 
                        status = kubernetes_asyncio.client.models.v1beta1/priority_level_configuration_status.v1beta1.PriorityLevelConfigurationStatus(
                            conditions = [
                                kubernetes_asyncio.client.models.v1beta1/priority_level_configuration_condition.v1beta1.PriorityLevelConfigurationCondition(
                                    last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    message = '', 
                                    reason = '', 
                                    type = '', )
                                ], ), )
                    ],
        )

    def testV1beta1PriorityLevelConfigurationList(self):
        """Test V1beta1PriorityLevelConfigurationList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
