# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.33.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta1_parent_reference import V1beta1ParentReference  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1beta1ParentReference(unittest.TestCase):
    """V1beta1ParentReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1beta1ParentReference
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1beta1_parent_reference.V1beta1ParentReference()  # noqa: E501
        if include_optional :
            return V1beta1ParentReference(
                group = '', 
                name = '', 
                namespace = '', 
                resource = ''
            )
        else :
            return V1beta1ParentReference(
                name = '',
                resource = '',
        )

    def testV1beta1ParentReference(self):
        """Test V1beta1ParentReference"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
