# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_namespace import V1Namespace  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1Namespace(unittest.TestCase):
    """V1Namespace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1Namespace(self):
        """Test V1Namespace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1_namespace.V1Namespace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
