# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.11
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1alpha1_cluster_cidr_spec import V1alpha1ClusterCIDRSpec  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1alpha1ClusterCIDRSpec(unittest.TestCase):
    """V1alpha1ClusterCIDRSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1ClusterCIDRSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1alpha1_cluster_cidr_spec.V1alpha1ClusterCIDRSpec()  # noqa: E501
        if include_optional :
            return V1alpha1ClusterCIDRSpec(
                ipv4 = '', 
                ipv6 = '', 
                node_selector = kubernetes_asyncio.client.models.v1/node_selector.v1.NodeSelector(
                    node_selector_terms = [
                        kubernetes_asyncio.client.models.v1/node_selector_term.v1.NodeSelectorTerm(
                            match_expressions = [
                                kubernetes_asyncio.client.models.v1/node_selector_requirement.v1.NodeSelectorRequirement(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_fields = [
                                kubernetes_asyncio.client.models.v1/node_selector_requirement.v1.NodeSelectorRequirement(
                                    key = '', 
                                    operator = '', )
                                ], )
                        ], ), 
                per_node_host_bits = 56
            )
        else :
            return V1alpha1ClusterCIDRSpec(
                per_node_host_bits = 56,
        )

    def testV1alpha1ClusterCIDRSpec(self):
        """Test V1alpha1ClusterCIDRSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
