# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.33.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v2_metric_spec import V2MetricSpec  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV2MetricSpec(unittest.TestCase):
    """V2MetricSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V2MetricSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v2_metric_spec.V2MetricSpec()  # noqa: E501
        if include_optional :
            return V2MetricSpec(
                container_resource = kubernetes_asyncio.client.models.v2/container_resource_metric_source.v2.ContainerResourceMetricSource(
                    container = '', 
                    name = '', 
                    target = kubernetes_asyncio.client.models.v2/metric_target.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ), 
                external = kubernetes_asyncio.client.models.v2/external_metric_source.v2.ExternalMetricSource(
                    metric = kubernetes_asyncio.client.models.v2/metric_identifier.v2.MetricIdentifier(
                        name = '', 
                        selector = kubernetes_asyncio.client.models.v1/label_selector.v1.LabelSelector(
                            match_expressions = [
                                kubernetes_asyncio.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), ), 
                    target = kubernetes_asyncio.client.models.v2/metric_target.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ), 
                object = kubernetes_asyncio.client.models.v2/object_metric_source.v2.ObjectMetricSource(
                    described_object = kubernetes_asyncio.client.models.v2/cross_version_object_reference.v2.CrossVersionObjectReference(
                        api_version = '', 
                        kind = '', 
                        name = '', ), 
                    metric = kubernetes_asyncio.client.models.v2/metric_identifier.v2.MetricIdentifier(
                        name = '', 
                        selector = kubernetes_asyncio.client.models.v1/label_selector.v1.LabelSelector(
                            match_expressions = [
                                kubernetes_asyncio.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), ), 
                    target = kubernetes_asyncio.client.models.v2/metric_target.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ), 
                pods = kubernetes_asyncio.client.models.v2/pods_metric_source.v2.PodsMetricSource(
                    metric = kubernetes_asyncio.client.models.v2/metric_identifier.v2.MetricIdentifier(
                        name = '', 
                        selector = kubernetes_asyncio.client.models.v1/label_selector.v1.LabelSelector(
                            match_expressions = [
                                kubernetes_asyncio.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), ), 
                    target = kubernetes_asyncio.client.models.v2/metric_target.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ), 
                resource = kubernetes_asyncio.client.models.v2/resource_metric_source.v2.ResourceMetricSource(
                    name = '', 
                    target = kubernetes_asyncio.client.models.v2/metric_target.v2.MetricTarget(
                        average_utilization = 56, 
                        average_value = '', 
                        type = '', 
                        value = '', ), ), 
                type = ''
            )
        else :
            return V2MetricSpec(
                type = '',
        )

    def testV2MetricSpec(self):
        """Test V2MetricSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
