# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.13.5
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_rolling_update_daemon_set import V1RollingUpdateDaemonSet  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1RollingUpdateDaemonSet(unittest.TestCase):
    """V1RollingUpdateDaemonSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1RollingUpdateDaemonSet(self):
        """Test V1RollingUpdateDaemonSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1_rolling_update_daemon_set.V1RollingUpdateDaemonSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
