# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.11.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_csi_persistent_volume_source import V1CSIPersistentVolumeSource  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1CSIPersistentVolumeSource(unittest.TestCase):
    """V1CSIPersistentVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CSIPersistentVolumeSource(self):
        """Test V1CSIPersistentVolumeSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1_csi_persistent_volume_source.V1CSIPersistentVolumeSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
