# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.11.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta1_ingress_tls import V1beta1IngressTLS  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1beta1IngressTLS(unittest.TestCase):
    """V1beta1IngressTLS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1IngressTLS(self):
        """Test V1beta1IngressTLS"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1beta1_ingress_tls.V1beta1IngressTLS()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
