# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.13.5
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_host_path_volume_source import V1HostPathVolumeSource  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1HostPathVolumeSource(unittest.TestCase):
    """V1HostPathVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1HostPathVolumeSource(self):
        """Test V1HostPathVolumeSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1_host_path_volume_source.V1HostPathVolumeSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
