# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.11.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta2_deployment_status import V1beta2DeploymentStatus  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1beta2DeploymentStatus(unittest.TestCase):
    """V1beta2DeploymentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta2DeploymentStatus(self):
        """Test V1beta2DeploymentStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1beta2_deployment_status.V1beta2DeploymentStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
