# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.11
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_mutating_webhook import V1MutatingWebhook  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1MutatingWebhook(unittest.TestCase):
    """V1MutatingWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1MutatingWebhook
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1_mutating_webhook.V1MutatingWebhook()  # noqa: E501
        if include_optional :
            return V1MutatingWebhook(
                admission_review_versions = [
                    ''
                    ], 
                kubernetes_asyncio.client_config = kubernetes_asyncio.client.models.admissionregistration/v1/webhook_client_config.admissionregistration.v1.WebhookClientConfig(
                    ca_bundle = 'YQ==', 
                    service = kubernetes_asyncio.client.models.admissionregistration/v1/service_reference.admissionregistration.v1.ServiceReference(
                        name = '', 
                        namespace = '', 
                        path = '', 
                        port = 56, ), 
                    url = '', ), 
                failure_policy = '', 
                match_policy = '', 
                name = '', 
                namespace_selector = kubernetes_asyncio.client.models.v1/label_selector.v1.LabelSelector(
                    match_expressions = [
                        kubernetes_asyncio.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                            key = '', 
                            operator = '', 
                            values = [
                                ''
                                ], )
                        ], 
                    match_labels = {
                        'key' : ''
                        }, ), 
                object_selector = kubernetes_asyncio.client.models.v1/label_selector.v1.LabelSelector(
                    match_expressions = [
                        kubernetes_asyncio.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                            key = '', 
                            operator = '', 
                            values = [
                                ''
                                ], )
                        ], 
                    match_labels = {
                        'key' : ''
                        }, ), 
                reinvocation_policy = '', 
                rules = [
                    kubernetes_asyncio.client.models.v1/rule_with_operations.v1.RuleWithOperations(
                        api_groups = [
                            ''
                            ], 
                        api_versions = [
                            ''
                            ], 
                        operations = [
                            ''
                            ], 
                        resources = [
                            ''
                            ], 
                        scope = '', )
                    ], 
                side_effects = '', 
                timeout_seconds = 56
            )
        else :
            return V1MutatingWebhook(
                admission_review_versions = [
                    ''
                    ],
                kubernetes_asyncio.client_config = kubernetes_asyncio.client.models.admissionregistration/v1/webhook_client_config.admissionregistration.v1.WebhookClientConfig(
                    ca_bundle = 'YQ==', 
                    service = kubernetes_asyncio.client.models.admissionregistration/v1/service_reference.admissionregistration.v1.ServiceReference(
                        name = '', 
                        namespace = '', 
                        path = '', 
                        port = 56, ), 
                    url = '', ),
                name = '',
                side_effects = '',
        )

    def testV1MutatingWebhook(self):
        """Test V1MutatingWebhook"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
