# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.33.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1alpha1_mutation import V1alpha1Mutation  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1alpha1Mutation(unittest.TestCase):
    """V1alpha1Mutation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1Mutation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1alpha1_mutation.V1alpha1Mutation()  # noqa: E501
        if include_optional :
            return V1alpha1Mutation(
                apply_configuration = kubernetes_asyncio.client.models.v1alpha1/apply_configuration.v1alpha1.ApplyConfiguration(
                    expression = '', ), 
                json_patch = kubernetes_asyncio.client.models.v1alpha1/json_patch.v1alpha1.JSONPatch(
                    expression = '', ), 
                patch_type = ''
            )
        else :
            return V1alpha1Mutation(
                patch_type = '',
        )

    def testV1alpha1Mutation(self):
        """Test V1alpha1Mutation"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
