# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1alpha1_role_list import V1alpha1RoleList  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1alpha1RoleList(unittest.TestCase):
    """V1alpha1RoleList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1RoleList(self):
        """Test V1alpha1RoleList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.v1alpha1_role_list.V1alpha1RoleList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
