# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.11
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_custom_resource_definition_status import V1CustomResourceDefinitionStatus  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1CustomResourceDefinitionStatus(unittest.TestCase):
    """V1CustomResourceDefinitionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1CustomResourceDefinitionStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1_custom_resource_definition_status.V1CustomResourceDefinitionStatus()  # noqa: E501
        if include_optional :
            return V1CustomResourceDefinitionStatus(
                accepted_names = kubernetes_asyncio.client.models.v1/custom_resource_definition_names.v1.CustomResourceDefinitionNames(
                    categories = [
                        ''
                        ], 
                    kind = '', 
                    list_kind = '', 
                    plural = '', 
                    short_names = [
                        ''
                        ], 
                    singular = '', ), 
                conditions = [
                    kubernetes_asyncio.client.models.v1/custom_resource_definition_condition.v1.CustomResourceDefinitionCondition(
                        last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        message = '', 
                        reason = '', 
                        status = '', 
                        type = '', )
                    ], 
                stored_versions = [
                    ''
                    ]
            )
        else :
            return V1CustomResourceDefinitionStatus(
        )

    def testV1CustomResourceDefinitionStatus(self):
        """Test V1CustomResourceDefinitionStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
