# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.12.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta1_stateful_set_condition import V1beta1StatefulSetCondition  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1beta1StatefulSetCondition(unittest.TestCase):
    """V1beta1StatefulSetCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1StatefulSetCondition(self):
        """Test V1beta1StatefulSetCondition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1beta1_stateful_set_condition.V1beta1StatefulSetCondition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
