# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.10.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes.client
from kubernetes.client.models.v1_persistent_volume_claim_condition import V1PersistentVolumeClaimCondition  # noqa: E501
from kubernetes.client.rest import ApiException


class TestV1PersistentVolumeClaimCondition(unittest.TestCase):
    """V1PersistentVolumeClaimCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PersistentVolumeClaimCondition(self):
        """Test V1PersistentVolumeClaimCondition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes.client.models.v1_persistent_volume_claim_condition.V1PersistentVolumeClaimCondition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
