# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.12.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.apps_v1beta1_deployment import AppsV1beta1Deployment  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestAppsV1beta1Deployment(unittest.TestCase):
    """AppsV1beta1Deployment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppsV1beta1Deployment(self):
        """Test AppsV1beta1Deployment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.apps_v1beta1_deployment.AppsV1beta1Deployment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
