# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.11
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v2_metric_target import V2MetricTarget  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV2MetricTarget(unittest.TestCase):
    """V2MetricTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V2MetricTarget
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v2_metric_target.V2MetricTarget()  # noqa: E501
        if include_optional :
            return V2MetricTarget(
                average_utilization = 56, 
                average_value = '', 
                type = '', 
                value = ''
            )
        else :
            return V2MetricTarget(
                type = '',
        )

    def testV2MetricTarget(self):
        """Test V2MetricTarget"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
