# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.11.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.apps_v1beta1_deployment_status import AppsV1beta1DeploymentStatus  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestAppsV1beta1DeploymentStatus(unittest.TestCase):
    """AppsV1beta1DeploymentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppsV1beta1DeploymentStatus(self):
        """Test AppsV1beta1DeploymentStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.apps_v1beta1_deployment_status.AppsV1beta1DeploymentStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
