# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.12.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta1_daemon_set_status import V1beta1DaemonSetStatus  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1beta1DaemonSetStatus(unittest.TestCase):
    """V1beta1DaemonSetStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1DaemonSetStatus(self):
        """Test V1beta1DaemonSetStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1beta1_daemon_set_status.V1beta1DaemonSetStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
