# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.33.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta2_network_device_data import V1beta2NetworkDeviceData  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException

class TestV1beta2NetworkDeviceData(unittest.TestCase):
    """V1beta2NetworkDeviceData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1beta2NetworkDeviceData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes_asyncio.client.models.v1beta2_network_device_data.V1beta2NetworkDeviceData()  # noqa: E501
        if include_optional :
            return V1beta2NetworkDeviceData(
                hardware_address = '', 
                interface_name = '', 
                ips = [
                    ''
                    ]
            )
        else :
            return V1beta2NetworkDeviceData(
        )

    def testV1beta2NetworkDeviceData(self):
        """Test V1beta2NetworkDeviceData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
