# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1.14.7
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.networking_v1beta1_ingress_rule import NetworkingV1beta1IngressRule  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestNetworkingV1beta1IngressRule(unittest.TestCase):
    """NetworkingV1beta1IngressRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkingV1beta1IngressRule(self):
        """Test NetworkingV1beta1IngressRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.networking_v1beta1_ingress_rule.NetworkingV1beta1IngressRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
