# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.11.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_replica_set_spec import V1ReplicaSetSpec  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1ReplicaSetSpec(unittest.TestCase):
    """V1ReplicaSetSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ReplicaSetSpec(self):
        """Test V1ReplicaSetSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1_replica_set_spec.V1ReplicaSetSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
