# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.12.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1_job_list import V1JobList  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1JobList(unittest.TestCase):
    """V1JobList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1JobList(self):
        """Test V1JobList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1_job_list.V1JobList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
