# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.12.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kubernetes_asyncio.client
from kubernetes_asyncio.client.models.v1beta1_role import V1beta1Role  # noqa: E501
from kubernetes_asyncio.client.rest import ApiException


class TestV1beta1Role(unittest.TestCase):
    """V1beta1Role unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1Role(self):
        """Test V1beta1Role"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kubernetes_asyncio.client.models.v1beta1_role.V1beta1Role()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
