import kubernetes_asyncio.client
import typing

class ApiextensionsV1Api:
    def __init__(self, api_client: typing.Optional[kubernetes_asyncio.client.api_client.ApiClient] = ...) -> None:
        ...
    async def get_api_resources(self) -> kubernetes_asyncio.client.V1APIResourceList:
        ...
    async def list_custom_resource_definition(self, *, pretty: typing.Optional[str] = ..., allow_watch_bookmarks: typing.Optional[bool] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CustomResourceDefinitionList:
        ...
    async def create_custom_resource_definition(self, body: kubernetes_asyncio.client.V1CustomResourceDefinition, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CustomResourceDefinition:
        ...
    async def delete_collection_custom_resource_definition(self, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., _continue: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def read_custom_resource_definition(self, name: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CustomResourceDefinition:
        ...
    async def replace_custom_resource_definition(self, name: str, body: kubernetes_asyncio.client.V1CustomResourceDefinition, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CustomResourceDefinition:
        ...
    async def delete_custom_resource_definition(self, name: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., dry_run: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def patch_custom_resource_definition(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CustomResourceDefinition:
        ...
    async def read_custom_resource_definition_status(self, name: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CustomResourceDefinition:
        ...
    async def replace_custom_resource_definition_status(self, name: str, body: kubernetes_asyncio.client.V1CustomResourceDefinition, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CustomResourceDefinition:
        ...
    async def patch_custom_resource_definition_status(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CustomResourceDefinition:
        ...
