import kubernetes_asyncio.client
import typing

class AutoscalingV1Api:
    def __init__(self, api_client: typing.Optional[kubernetes_asyncio.client.api_client.ApiClient] = ...) -> None:
        ...
    async def get_api_resources(self) -> kubernetes_asyncio.client.V1APIResourceList:
        ...
    async def list_horizontal_pod_autoscaler_for_all_namespaces(self, *, allow_watch_bookmarks: typing.Optional[bool] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., pretty: typing.Optional[str] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1HorizontalPodAutoscalerList:
        ...
    async def list_namespaced_horizontal_pod_autoscaler(self, namespace: str, *, pretty: typing.Optional[str] = ..., allow_watch_bookmarks: typing.Optional[bool] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1HorizontalPodAutoscalerList:
        ...
    async def create_namespaced_horizontal_pod_autoscaler(self, namespace: str, body: kubernetes_asyncio.client.V1HorizontalPodAutoscaler, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1HorizontalPodAutoscaler:
        ...
    async def delete_collection_namespaced_horizontal_pod_autoscaler(self, namespace: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., _continue: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def read_namespaced_horizontal_pod_autoscaler(self, name: str, namespace: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1HorizontalPodAutoscaler:
        ...
    async def replace_namespaced_horizontal_pod_autoscaler(self, name: str, namespace: str, body: kubernetes_asyncio.client.V1HorizontalPodAutoscaler, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1HorizontalPodAutoscaler:
        ...
    async def delete_namespaced_horizontal_pod_autoscaler(self, name: str, namespace: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., dry_run: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def patch_namespaced_horizontal_pod_autoscaler(self, name: str, namespace: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1HorizontalPodAutoscaler:
        ...
    async def read_namespaced_horizontal_pod_autoscaler_status(self, name: str, namespace: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1HorizontalPodAutoscaler:
        ...
    async def replace_namespaced_horizontal_pod_autoscaler_status(self, name: str, namespace: str, body: kubernetes_asyncio.client.V1HorizontalPodAutoscaler, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1HorizontalPodAutoscaler:
        ...
    async def patch_namespaced_horizontal_pod_autoscaler_status(self, name: str, namespace: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1HorizontalPodAutoscaler:
        ...
