import kubernetes_asyncio.client
import typing

class StorageV1Api:
    def __init__(self, api_client: typing.Optional[kubernetes_asyncio.client.api_client.ApiClient] = ...) -> None:
        ...
    async def get_api_resources(self) -> kubernetes_asyncio.client.V1APIResourceList:
        ...
    async def list_csi_driver(self, *, pretty: typing.Optional[str] = ..., allow_watch_bookmarks: typing.Optional[bool] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CSIDriverList:
        ...
    async def create_csi_driver(self, body: kubernetes_asyncio.client.V1CSIDriver, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSIDriver:
        ...
    async def delete_collection_csi_driver(self, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., _continue: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def read_csi_driver(self, name: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSIDriver:
        ...
    async def replace_csi_driver(self, name: str, body: kubernetes_asyncio.client.V1CSIDriver, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSIDriver:
        ...
    async def delete_csi_driver(self, name: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., dry_run: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSIDriver:
        ...
    async def patch_csi_driver(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CSIDriver:
        ...
    async def list_csi_node(self, *, pretty: typing.Optional[str] = ..., allow_watch_bookmarks: typing.Optional[bool] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CSINodeList:
        ...
    async def create_csi_node(self, body: kubernetes_asyncio.client.V1CSINode, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSINode:
        ...
    async def delete_collection_csi_node(self, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., _continue: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def read_csi_node(self, name: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSINode:
        ...
    async def replace_csi_node(self, name: str, body: kubernetes_asyncio.client.V1CSINode, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSINode:
        ...
    async def delete_csi_node(self, name: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., dry_run: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSINode:
        ...
    async def patch_csi_node(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CSINode:
        ...
    async def list_csi_storage_capacity_for_all_namespaces(self, *, allow_watch_bookmarks: typing.Optional[bool] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., pretty: typing.Optional[str] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CSIStorageCapacityList:
        ...
    async def list_namespaced_csi_storage_capacity(self, namespace: str, *, pretty: typing.Optional[str] = ..., allow_watch_bookmarks: typing.Optional[bool] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CSIStorageCapacityList:
        ...
    async def create_namespaced_csi_storage_capacity(self, namespace: str, body: kubernetes_asyncio.client.V1CSIStorageCapacity, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSIStorageCapacity:
        ...
    async def delete_collection_namespaced_csi_storage_capacity(self, namespace: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., _continue: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def read_namespaced_csi_storage_capacity(self, name: str, namespace: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSIStorageCapacity:
        ...
    async def replace_namespaced_csi_storage_capacity(self, name: str, namespace: str, body: kubernetes_asyncio.client.V1CSIStorageCapacity, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1CSIStorageCapacity:
        ...
    async def delete_namespaced_csi_storage_capacity(self, name: str, namespace: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., dry_run: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def patch_namespaced_csi_storage_capacity(self, name: str, namespace: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1CSIStorageCapacity:
        ...
    async def list_storage_class(self, *, pretty: typing.Optional[str] = ..., allow_watch_bookmarks: typing.Optional[bool] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1StorageClassList:
        ...
    async def create_storage_class(self, body: kubernetes_asyncio.client.V1StorageClass, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1StorageClass:
        ...
    async def delete_collection_storage_class(self, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., _continue: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def read_storage_class(self, name: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1StorageClass:
        ...
    async def replace_storage_class(self, name: str, body: kubernetes_asyncio.client.V1StorageClass, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1StorageClass:
        ...
    async def delete_storage_class(self, name: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., dry_run: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1StorageClass:
        ...
    async def patch_storage_class(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1StorageClass:
        ...
    async def list_volume_attachment(self, *, pretty: typing.Optional[str] = ..., allow_watch_bookmarks: typing.Optional[bool] = ..., _continue: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ..., watch: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1VolumeAttachmentList:
        ...
    async def create_volume_attachment(self, body: kubernetes_asyncio.client.V1VolumeAttachment, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1VolumeAttachment:
        ...
    async def delete_collection_volume_attachment(self, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., _continue: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_selector: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., label_selector: typing.Optional[str] = ..., limit: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ..., resource_version: typing.Optional[str] = ..., resource_version_match: typing.Optional[str] = ..., timeout_seconds: typing.Optional[int] = ...) -> kubernetes_asyncio.client.V1Status:
        ...
    async def read_volume_attachment(self, name: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1VolumeAttachment:
        ...
    async def replace_volume_attachment(self, name: str, body: kubernetes_asyncio.client.V1VolumeAttachment, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1VolumeAttachment:
        ...
    async def delete_volume_attachment(self, name: str, *, pretty: typing.Optional[str] = ..., body: typing.Optional[kubernetes_asyncio.client.V1DeleteOptions] = ..., dry_run: typing.Optional[str] = ..., grace_period_seconds: typing.Optional[int] = ..., orphan_dependents: typing.Optional[bool] = ..., propagation_policy: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1VolumeAttachment:
        ...
    async def patch_volume_attachment(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1VolumeAttachment:
        ...
    async def read_volume_attachment_status(self, name: str, *, pretty: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1VolumeAttachment:
        ...
    async def replace_volume_attachment_status(self, name: str, body: kubernetes_asyncio.client.V1VolumeAttachment, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ...) -> kubernetes_asyncio.client.V1VolumeAttachment:
        ...
    async def patch_volume_attachment_status(self, name: str, body: typing.Any, *, pretty: typing.Optional[str] = ..., dry_run: typing.Optional[str] = ..., field_manager: typing.Optional[str] = ..., field_validation: typing.Optional[str] = ..., force: typing.Optional[bool] = ...) -> kubernetes_asyncio.client.V1VolumeAttachment:
        ...
